// dashboard/src/components/ui/AssignmentTable.tsx
import { useState } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import SubmitAssignmentDialog from "@/components/ui/SubmitAssignmentDialog";
import SubmissionPreviewDialog from "@/components/ui/SubmissionPreviewDialog";
import { formatDateTime } from "@/lib/dayjs";
import { useNavigate } from "react-router-dom";

interface Assignment {
  name: string;
  title: string;
  due_date: string;
  max_marks: number;
  assignment_type?: string;
  submission_type?: string;
}

interface Submission {
  name: string;
  assignment: string;
  submitted_at: string;
  submission_document?: string;
  submission_url?: string;
}

interface Props {
  assignments: Assignment[];
  submissionMap: Record<string, Submission>;
  gradeMap?: Record<string, any>;
  onSubmitSuccess: () => void;
  onViewGrade?: (assignmentName: string) => void;
}

function getStatus(
  assignment: Assignment,
  submission: Submission | undefined,
  isGraded: boolean,
) {
  if (isGraded) return "closed";
  if (submission) return "submitted";
  if (new Date(assignment.due_date) < new Date()) return "closed";
  return "pending";
}

export default function AssignmentTable({
  assignments,
  submissionMap,
  gradeMap,
  onSubmitSuccess,
  onViewGrade,
}: Props) {
  const [dialogAssignment, setDialogAssignment] = useState<Assignment | null>(
    null,
  );
  const [editSubmission, setEditSubmission] = useState<Submission | null>(null);
  const [previewAssignment, setPreviewAssignment] = useState<Assignment | null>(
    null,
  );
  const [previewSubmission, setPreviewSubmission] = useState<Submission | null>(
    null,
  );
  const navigate = useNavigate();

  return (
    <>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Title</TableHead>
            <TableHead>Due</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Submitted</TableHead>
            <TableHead className="text-right"></TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {assignments.length === 0 && (
            <TableRow>
              <TableCell
                colSpan={5}
                className="text-center text-muted-foreground py-8"
              >
                No assignments yet.
              </TableCell>
            </TableRow>
          )}
          {assignments.map((a) => {
            const submission = submissionMap[a.name];
            const isGraded = !!gradeMap?.[a.name];
            const status = getStatus(a, submission, isGraded);

            return (
              <TableRow key={a.name}>
                <TableCell className="font-medium">
                  <button
                    className="text-left hover:underline"
                    onClick={() =>
                      navigate(`/assignments/${a.name}/submission`)
                    }
                  >
                    {a.title}
                  </button>
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {formatDateTime(a.due_date)}
                </TableCell>
                <TableCell>
                  {status === "submitted" && (
                    <Badge variant="default">Submitted</Badge>
                  )}
                  {status === "closed" && (
                    <Badge variant="outline">Closed</Badge>
                  )}
                  {status === "pending" && (
                    <Badge variant="secondary">Pending</Badge>
                  )}
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">
                  {submission ? formatDateTime(submission.submitted_at) : null}
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex items-center justify-end gap-2">
                    {submission && (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => {
                          setPreviewAssignment(a);
                          setPreviewSubmission(submission);
                        }}
                      >
                        Preview
                      </Button>
                    )}
                    {status === "closed" && isGraded && onViewGrade && a.assignment_type !== "Not Graded" ? (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => onViewGrade(a.name)}
                      >
                        View Grade
                      </Button>
                    ) : status === "submitted" ? (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => {
                          setDialogAssignment(a);
                          setEditSubmission(submission);
                        }}
                      >
                        Edit
                      </Button>
                    ) : status === "pending" ? (
                      <Button
                        size="sm"
                        onClick={() => {
                          setDialogAssignment(a);
                          setEditSubmission(null);
                        }}
                      >
                        Submit
                      </Button>
                    ) : null}
                  </div>
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>

      {dialogAssignment && (
        <SubmitAssignmentDialog
          open={!!dialogAssignment}
          onOpenChange={(open) => {
            if (!open) {
              setDialogAssignment(null);
              setEditSubmission(null);
            }
          }}
          assignment={dialogAssignment}
          existingSubmission={editSubmission}
          onSuccess={() => {
            setDialogAssignment(null);
            setEditSubmission(null);
            onSubmitSuccess();
          }}
        />
      )}

      {previewAssignment && (
        <SubmissionPreviewDialog
          open={!!previewAssignment}
          onOpenChange={(open) => {
            if (!open) {
              setPreviewAssignment(null);
              setPreviewSubmission(null);
            }
          }}
          title={`Your Submission: ${previewAssignment.title}`}
          submissionType={previewAssignment.submission_type}
          fileUrl={
            previewSubmission?.submission_document ||
            previewSubmission?.submission_url
          }
        />
      )}
    </>
  );
}

// dashboard/src/components/assignments/AssignmentTable.vue
<template>
	<DataTable
		:columns="columns"
		:rows="assignments"
		:row-key="rowKey"
		:loading="loading"
		empty="No assignments yet."
	>
		<template #cell-title="{ row }">
			<RouterLink
				:to="`/assignments/${row.name}/submission`"
				class="truncate text-ink-gray-8 hover:underline"
			>
				{{ row.title }}
			</RouterLink>
		</template>

		<template #cell-due="{ row }">
			<span class="text-ink-gray-6">{{ formatDateTime(row.due_date) }}</span>
		</template>

		<template #cell-status="{ row }">
			<Badge
				:label="statusOf(row)"
				:theme="assignmentStatusTheme(statusOf(row))"
				variant="subtle"
			/>
		</template>

		<template #cell-submitted="{ row }">
			<span class="text-ink-gray-6">{{
				formatDateTime(submissionMap[row.name]?.submitted_at)
			}}</span>
		</template>

		<template #cell-actions="{ row }">
			<div class="flex items-center justify-end gap-2">
				<Button
					v-if="submissionMap[row.name]"
					label="Preview"
					@click="openPreview(row, submissionMap[row.name])"
				/>
				<Button
					v-if="showsGrade(row)"
					label="View Grade"
					@click="emit('view-grade', row.name)"
				/>
				<Button
					v-else-if="statusOf(row) === 'Submitted' && !isScratch(row)"
					variant="outline"
					label="Edit"
					@click="openSubmit(row, submissionMap[row.name])"
				/>
				<Button
					v-else-if="statusOf(row) === 'Pending'"
					variant="solid"
					theme="gray"
					label="Submit"
					@click="openSubmit(row, null)"
				/>
			</div>
		</template>
	</DataTable>

	<SubmitAssignmentDialog
		v-if="submitAssignment"
		v-model:open="submitOpen"
		:assignment="submitAssignment"
		:existing-submission="submitSubmission"
		@success="onSubmitted"
	/>

	<SubmissionPreviewDialog
		v-if="previewAssignment"
		v-model:open="previewOpen"
		:title="`Your Submission: ${previewAssignment.title}`"
		:submission-type="previewAssignment.submission_type"
		:file-url="previewSubmission?.submission_document || previewSubmission?.submission_url"
		:submission="previewSubmission?.name"
	/>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Badge, Button } from 'frappe-ui'
import DataTable, { type Column } from '@/components/common/DataTable.vue'
import SubmissionPreviewDialog from '@/components/assignments/SubmissionPreviewDialog.vue'
import SubmitAssignmentDialog from '@/components/assignments/SubmitAssignmentDialog.vue'
import { useScratchAssignment } from '@/components/assignments/scratchEditor'
import { formatDateTime } from '@/lib/dates'
import { assignmentStatus, assignmentStatusTheme } from '@/lib/status'
import type { CS17Assignment, CS17Grade, CS17Submission } from '@/types'

const props = defineProps<{
	assignments: CS17Assignment[]
	/** The student's own submissions, keyed by assignment. */
	submissionMap: Record<string, CS17Submission>
	/** The grades they are allowed to see, keyed by assignment. */
	gradeMap?: Record<string, CS17Grade>
	loading?: boolean
}>()

const emit = defineEmits<{
	/** A submission was created or edited; the parent reloads its data. */
	submitted: []
	/** The student asked to see the grade for this assignment. */
	'view-grade': [assignment: string]
}>()

const columns: Column[] = [
	{ header: 'Title', key: 'title', variant: 'primary' },
	{ header: 'Due', key: 'due', width: '11rem' },
	{ header: 'Status', key: 'status', width: '8rem' },
	{ header: 'Submitted', key: 'submitted', width: '11rem' },
	{ header: '', key: 'actions', variant: 'actions', width: '12rem', align: 'right' },
]

const rowKey = (row: CS17Assignment) => row.name

const scratch = useScratchAssignment()

const submitOpen = ref(false)
const submitAssignment = ref<CS17Assignment | null>(null)
const submitSubmission = ref<CS17Submission | null>(null)

const previewOpen = ref(false)
const previewAssignment = ref<CS17Assignment | null>(null)
const previewSubmission = ref<CS17Submission | null>(null)

/** The ladder is imported, never re-derived — three surfaces have to agree. */
function statusOf(assignment: CS17Assignment) {
	return assignmentStatus(
		assignment,
		props.submissionMap[assignment.name],
		props.gradeMap?.[assignment.name],
	)
}

function isScratch(assignment: CS17Assignment): boolean {
	return assignment.submission_type === 'Scratch'
}

/** A Not Graded assignment closes without a grade, so it offers nothing to view. */
function showsGrade(assignment: CS17Assignment): boolean {
	return (
		statusOf(assignment) === 'Closed' &&
		Boolean(props.gradeMap?.[assignment.name]) &&
		assignment.assignment_type !== 'Not Graded'
	)
}

function openSubmit(assignment: CS17Assignment, existing: CS17Submission | null) {
	if (isScratch(assignment)) {
		scratch.open(assignment, existing)
		return
	}
	submitAssignment.value = assignment
	submitSubmission.value = existing
	submitOpen.value = true
}

function openPreview(assignment: CS17Assignment, submission: CS17Submission) {
	if (isScratch(assignment)) {
		// A closed Scratch assignment opens in the player rather than the editor.
		scratch.open(assignment, submission, {
			readOnly: statusOf(assignment) === 'Closed',
		})
		return
	}
	previewAssignment.value = assignment
	previewSubmission.value = submission
	previewOpen.value = true
}

function onSubmitted() {
	submitOpen.value = false
	emit('submitted')
}
</script>
