// dashboard-react/src/components/ui/SubmissionPreviewDialog.tsx
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";
import { previewKind } from "@/lib/submissionTypes";
import ScratchSubmissionPlayer from "@/components/ui/ScratchSubmissionPlayer";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  submissionType?: string;
  fileUrl?: string | null;
  submission?: string | null;
}

export default function SubmissionPreviewDialog({
  open,
  onOpenChange,
  title,
  submissionType,
  fileUrl,
  submission,
}: Props) {
  const isScratch = submissionType === "Scratch" && !!submission;
  const kind = previewKind(submissionType, fileUrl);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className={
          isScratch
            ? "flex h-[92vh] w-[96vw] max-w-[96vw] flex-col sm:max-w-[96vw]"
            : "max-w-2xl"
        }
      >
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
        </DialogHeader>
        <div className={isScratch ? "min-h-0 flex-1 pt-2" : "py-2"}>
          {isScratch ? (
            <div className="h-full overflow-hidden rounded-md border border-border">
              <ScratchSubmissionPlayer submission={submission} />
            </div>
          ) : !fileUrl ? (
            <p className="text-sm text-muted-foreground">
              No submission found.
            </p>
          ) : kind === "image" ? (
            <img
              src={fileUrl}
              alt="Submission preview"
              className="max-h-[60vh] w-full rounded-md border border-border object-contain"
            />
          ) : kind === "pdf" ? (
            <iframe
              src={fileUrl}
              title="Submission preview"
              className="h-[60vh] w-full rounded-md border border-border"
            />
          ) : (
            <OpenLink url={fileUrl} isUrl={kind === "url"} />
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

function OpenLink({ url, isUrl }: { url: string; isUrl: boolean }) {
  return (
    <div className="space-y-3">
      {isUrl && (
        <p className="text-sm text-muted-foreground break-all">{url}</p>
      )}
      <a href={url} target="_blank" rel="noopener noreferrer">
        <Button variant="outline" className="w-full">
          <ExternalLink className="w-4 h-4 mr-2" />
          {isUrl ? "Open link" : "Open file"}
        </Button>
      </a>
    </div>
  );
}

// dashboard/src/components/assignments/SubmissionPreviewDialog.vue
<template>
	<Dialog
		:open="open"
		:title="title"
		:size="isScratch ? '6xl' : '2xl'"
		@update:open="emit('update:open', $event)"
	>
		<!-- A Scratch submission is a project, not a file: it plays in the
		     read-only editor, everything else is a document or a link. -->
		<div
			v-if="isScratch"
			class="h-[70vh] overflow-hidden rounded-4 border border-outline-gray-1"
		>
			<p v-if="projectError" class="p-6 text-p-base text-ink-gray-5">
				Could not load the submitted project.
			</p>
			<Skeleton v-else-if="!sb3" class="h-full w-full" />
			<ScratchFrame v-else :sb3="sb3" read-only />
		</div>

		<p v-else-if="!fileUrl" class="text-p-base text-ink-gray-5">No submission found.</p>

		<img
			v-else-if="kind === 'image'"
			:src="fileUrl"
			alt="Submission preview"
			class="max-h-[60vh] w-full rounded-4 border border-outline-gray-1 object-contain"
		/>

		<iframe
			v-else-if="kind === 'pdf'"
			:src="fileUrl"
			title="Submission preview"
			class="h-[60vh] w-full rounded-4 border border-outline-gray-1"
		/>

		<div v-else class="space-y-3">
			<p v-if="kind === 'url'" class="break-all text-p-base text-ink-gray-5">{{ fileUrl }}</p>
			<Button
				class="w-full"
				icon-left="lucide-external-link"
				:label="kind === 'url' ? 'Open link' : 'Open file'"
				:href="fileUrl"
			/>
		</div>
	</Dialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Button, Dialog, Skeleton, useCall } from 'frappe-ui'
import ScratchFrame from '@/components/scratch/ScratchFrame.vue'
import { base64ToArrayBuffer } from '@/lib/scratch'
import { previewKind } from '@/lib/submissionTypes'

const props = defineProps<{
	open: boolean
	title: string
	submissionType?: string
	/** The stored file, or the submitted link for a URL assignment. */
	fileUrl?: string | null
	/** The submission name — only a Scratch submission needs it. */
	submission?: string | null
}>()

const emit = defineEmits<{ 'update:open': [value: boolean] }>()

const isScratch = computed(() => props.submissionType === 'Scratch' && Boolean(props.submission))
const kind = computed(() => previewKind(props.submissionType, props.fileUrl))

const sb3 = ref<ArrayBuffer | null>(null)

const projectCall = useCall<{ filename: string; content: string }, { submission: string }>({
	url: '/api/v2/method/cs17_portal.api.get_submission_project',
	params: () => ({ submission: props.submission ?? '' }),
	immediate: false,
	onSuccess: (data) => {
		sb3.value = data.content ? base64ToArrayBuffer(data.content) : null
	},
})

const projectError = computed(() => Boolean(projectCall.error))

// The project is a base64 payload of its own, so it is fetched when the dialog
// actually opens rather than for every row of the table behind it.
watch(
	() => [props.open, props.submission] as const,
	([isOpen]) => {
		if (!isOpen || !isScratch.value) return
		sb3.value = null
		projectCall.reload()
	},
	{ immediate: true },
)
</script>
