// dashboard/src/pages/AssignmentDetailPage.vue
<template>
	<AppHeader :title="assignment?.title ?? 'Assignment'">
		<template #left-mobile>
			<PageHeaderBackButton fallback-route="/assignments" />
		</template>
	</AppHeader>

	<div class="px-3 py-5 pb-10 sm:px-5">
		<PageSkeleton v-if="loading" :blocks="2" />

		<p v-else-if="!assignment" class="text-p-base text-ink-gray-5">Assignment not found.</p>

		<div v-else class="flex flex-col gap-6 md:flex-row">
			<div class="min-w-0 flex-1">
				<h1 class="mb-4 text-2xl text-ink-gray-9">{{ assignment.title }}</h1>
				<MarkdownText :content="assignment.description" />
			</div>

			<!-- The meta panel: everything about the assignment that is a value
			     rather than prose, plus the one action the student can take. -->
			<div
				class="w-full shrink-0 space-y-3 rounded-4 border border-outline-gray-1 p-4 md:w-64"
			>
				<div>
					<p class="text-xs text-ink-gray-5">Due</p>
					<p
						:class="
							isOverdue ? 'text-base text-ink-red-6' : 'text-base text-ink-gray-8'
						"
					>
						{{ formatDateTime(assignment.due_date) }}
					</p>
				</div>

				<div>
					<p class="text-xs text-ink-gray-5">Evaluation Type</p>
					<p class="text-base text-ink-gray-8">{{ evaluationType }}</p>
				</div>

				<div v-if="evaluationType === 'Marks'">
					<p class="text-xs text-ink-gray-5">Max Marks</p>
					<p class="text-base text-ink-gray-8">{{ assignment.max_marks }}</p>
				</div>

				<template v-if="submission">
					<div>
						<p class="text-xs text-ink-gray-5">Submitted</p>
						<p class="text-base text-ink-green-6">
							{{ formatDateTime(submission.submitted_at) }}
						</p>
					</div>

					<Button
						v-if="!isOverdue && !grade"
						class="w-full"
						variant="outline"
						label="Edit Submission"
						@click="openSubmit"
					/>

					<template v-if="grade">
						<div>
							<p class="text-xs text-ink-gray-5">
								{{ isLetterGrade ? 'Grade' : 'Marks Obtained' }}
							</p>
							<p class="text-lg text-ink-gray-9">{{ score }}</p>
						</div>
						<div v-if="grade.remarks">
							<p class="text-xs text-ink-gray-5">Remarks</p>
							<p class="mt-0.5 text-p-base text-ink-gray-8">{{ grade.remarks }}</p>
						</div>
					</template>
				</template>

				<Button
					v-else
					class="w-full"
					variant="outline"
					:disabled="isOverdue"
					:label="isOverdue ? 'Deadline Passed' : 'Submit Assignment'"
					@click="openSubmit"
				/>
			</div>
		</div>

		<SubmitAssignmentDialog
			v-if="assignment"
			v-model:open="submitOpen"
			:assignment="assignment"
			:existing-submission="submission"
			@success="onSubmitted"
		/>
	</div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Button, PageHeaderBackButton, useCall, useDoc, useList } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import MarkdownText from '@/components/common/MarkdownText.vue'
import PageSkeleton from '@/components/common/PageSkeleton.vue'
import SubmitAssignmentDialog from '@/components/assignments/SubmitAssignmentDialog.vue'
import { useScratchAssignment } from '@/components/assignments/scratchEditor'
import { useBreadcrumbs } from '@/composables/useBreadcrumbs'
import { useSession } from '@/composables/useSession'
import { formatDateTime, isPast } from '@/lib/dates'
import type { CS17Assignment, CS17Submission, StudentGradesResponse } from '@/types'

const props = defineProps<{ assignmentId: string }>()

const { profile } = useSession()
const breadcrumbs = useBreadcrumbs()
const scratch = useScratchAssignment()

const assignmentDoc = useDoc<CS17Assignment>({
	doctype: 'CS17 Assignment',
	name: () => props.assignmentId,
})

const submissions = useList<CS17Submission>({
	doctype: 'CS17 Assignment Submission',
	fields: ['name', 'student', 'assignment', 'submitted_at', 'project'],
	filters: () => ({ student: profile.value?.name ?? '', assignment: props.assignmentId }),
	limit: 1,
	immediate: Boolean(profile.value?.name),
})

const gradesCall = useCall<StudentGradesResponse>({
	url: '/api/v2/method/cs17_portal.api.get_student_grades',
})

const assignment = computed(() => assignmentDoc.doc)
const loading = computed(() => assignmentDoc.loading && !assignmentDoc.doc)
const submission = computed(() => submissions.data?.[0] ?? null)

/**
 * Only the grade written against this student's own submission counts — the
 * endpoint answers with every grade they may see, across assignments.
 */
const grade = computed(
	() => gradesCall.data?.grades.find((row) => row.submission === submission.value?.name) ?? null,
)

const isLetterGrade = computed(() => grade.value?.evaluation_type === 'Grade')
const score = computed(() => {
	const value = isLetterGrade.value ? grade.value?.grade : grade.value?.marks_obtained
	return value === null || value === undefined ? '—' : String(value)
})

const isOverdue = computed(() => isPast(assignment.value?.due_date))

/** `remarks` is the doctype's field for how a graded assignment is scored. */
const evaluationType = computed(() =>
	assignment.value?.assignment_type === 'Graded'
		? (assignment.value.remarks ?? 'Graded')
		: 'Non-graded',
)

const submitOpen = ref(false)

function openSubmit() {
	if (!assignment.value) return
	// Scratch work is done in the editor, so this row jumps there instead.
	if (assignment.value.submission_type === 'Scratch') {
		scratch.open(assignment.value, submission.value)
		return
	}
	submitOpen.value = true
}

function onSubmitted() {
	submitOpen.value = false
	submissions.reload()
	gradesCall.reload()
}

watch(
	() => assignment.value?.title,
	(title) => {
		if (!title) return
		breadcrumbs.set([{ label: 'Assignments', route: '/assignments' }, { label: title }])
	},
	{ immediate: true },
)
</script>

// dashboard/src/pages/AssignmentDetailPage.tsx
import { useParams, useNavigate } from "react-router-dom";
import { useFrappeGetDoc, useFrappeGetDocList } from "frappe-react-sdk";
import { useCurrentStudent } from "@/hooks/useCurrentStudent";
import { useStudentGrades } from "@/hooks/useStudentGrades";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import SubmitAssignmentDialog from "@/components/ui/SubmitAssignmentDialog";
import RichText from "@/components/ui/RichText";
import { formatDateTime } from "@/lib/dayjs";
import { ArrowLeft } from "lucide-react";
import { useBreadcrumb } from "@/context/BreadcrumbContext";
import { useScratchEditor } from "@/hooks/useScratchEditor";
import { useEffect } from "react";

export default function AssignmentDetailPage() {
  const { assignmentId } = useParams<{ assignmentId: string }>();
  const { student } = useCurrentStudent();
  const [dialogOpen, setDialogOpen] = useState(false);
  const navigate = useNavigate();
  const scratch = useScratchEditor();
  const { setBreadcrumb } = useBreadcrumb();

  const { data: assignment, isLoading: assignmentLoading } = useFrappeGetDoc(
    "CS17 Assignment",
    assignmentId,
  );

  const { data: submissions, mutate } = useFrappeGetDocList(
    "CS17 Assignment Submission",
    {
      filters: [
        ["student", "=", student?.name ?? ""],
        ["assignment", "=", assignmentId ?? ""],
      ],
      fields: ["name", "assignment", "submitted_at", "modified", "project"],
      limit: 1,
    },
    student?.name && assignmentId ? undefined : null,
  );

  const submission = submissions?.[0] ?? null;

  const { grades } = useStudentGrades(!!student?.name);

  const gradeDoc = grades.find((g) => g.submission === submission?.name) ?? null;
  const isGraded = !!gradeDoc;

  useEffect(() => {
    if (!assignment) return;
    setBreadcrumb([
      { label: "Assignments", href: "/assignments" },
      { label: assignment.title },
    ]);
    return () => setBreadcrumb([]);
  }, [assignment?.title]);

  if (assignmentLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-1/2" />
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-3/4" />
      </div>
    );
  }

  if (!assignment) {
    return <p className="text-muted-foreground">Assignment not found.</p>;
  }

  const isOverdue = new Date(assignment.due_date) < new Date();
  const evaluationType =
    assignment.assignment_type === "Graded" ? assignment.remarks : "Non-graded";

  return (
    <div className="space-y-4">
      <button
        onClick={() => navigate("/assignments")}
        className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Assignments
      </button>

      <div className="flex flex-col md:flex-row gap-6">
        <div className="flex-1 min-w-0">
          <h1 className="text-2xl font-bold mb-4">{assignment.title}</h1>
          <RichText content={assignment.description} />
        </div>

        <div className="w-full md:w-64 shrink-0 space-y-4">
          <div className="border border-border rounded-xl p-4 space-y-3">
            <div>
              <p className="text-xs text-muted-foreground">Due</p>
              <p
                className={`text-sm font-medium ${isOverdue ? "text-destructive" : ""}`}
              >
                {formatDateTime(assignment.due_date)}
              </p>
            </div>

            <div>
              <p className="text-xs text-muted-foreground">Evaluation Type</p>
              <p className="text-sm font-medium">{evaluationType}</p>
            </div>

            {evaluationType === "Marks" && (
              <div>
                <p className="text-xs text-muted-foreground">Max Marks</p>
                <p className="text-sm font-medium">{assignment.max_marks}</p>
              </div>
            )}

            {submission ? (
              <>
                <div>
                  <p className="text-xs text-muted-foreground">Submitted</p>
                  <p className="text-sm font-medium text-green-600">
                    {formatDateTime(submission.submitted_at)}
                  </p>
                </div>
                {!isOverdue && !isGraded && (
                  <Button
                    variant="outline"
                    className="w-full"
                    onClick={() => setDialogOpen(true)}
                  >
                    Edit Submission
                  </Button>
                )}
                {gradeDoc && (
                  <>
                    {gradeDoc.evaluation_type === "Grade" ? (
                      <div>
                        <p className="text-xs text-muted-foreground">Grade</p>
                        <p className="text-lg font-semibold">{gradeDoc.grade ?? "—"}</p>
                      </div>
                    ) : (
                      <div>
                        <p className="text-xs text-muted-foreground">Marks Obtained</p>
                        <p className="text-lg font-semibold">{gradeDoc.marks_obtained ?? "—"}</p>
                      </div>
                    )}
                    {gradeDoc.remarks && (
                      <div>
                        <p className="text-xs text-muted-foreground">Remarks</p>
                        <p className="text-sm mt-0.5">{gradeDoc.remarks}</p>
                      </div>
                    )}
                  </>
                )}
              </>
            ) : (
              <Button
                variant="outline"
                className="w-full"
                disabled={isOverdue}
                onClick={() =>
                  assignment.submission_type === "Scratch"
                    ? scratch.open(assignment, submission)
                    : setDialogOpen(true)
                }
              >
                {isOverdue ? "Deadline Passed" : "Submit Assignment"}
              </Button>
            )}
          </div>
        </div>
      </div>

      <SubmitAssignmentDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        assignment={assignment}
        existingSubmission={submission}
        onSuccess={() => {
          setDialogOpen(false);
          mutate();
        }}
      />
    </div>
  );
}
