// dashboard/src/faculty/FacultySubmissionsPage.tsx
import { useNavigate } from "react-router-dom";
import { useFrappeGetCall } from "frappe-react-sdk";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDateTime } from "@/lib/dayjs";
import { GradeBadge } from "./GradeBadge";
import type { CohortSubmission } from "./types";

export default function FacultySubmissionsPage() {
  const navigate = useNavigate();

  const { data: submissionsData, isLoading } = useFrappeGetCall<{
    message: CohortSubmission[];
  }>("cs17_portal.api.list_cohort_submissions");
  const submissions = submissionsData?.message ?? [];

  function openGrading(submission: CohortSubmission) {
    navigate(`/faculty/submissions/${submission.name}`);
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Submissions</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Open, run, and grade submissions from your cohort.
        </p>
      </div>

      <div className="rounded-xl border border-border bg-background p-2">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Student</TableHead>
              <TableHead>Assignment</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Submitted</TableHead>
              <TableHead>Grade</TableHead>
              <TableHead className="text-right"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              [0, 1, 2].map((i) => (
                <TableRow key={i}>
                  <TableCell colSpan={6}>
                    <Skeleton className="h-8 w-full" />
                  </TableCell>
                </TableRow>
              ))
            ) : submissions.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="py-8 text-center text-muted-foreground">
                  No submissions yet.
                </TableCell>
              </TableRow>
            ) : (
              submissions.map((submission) => (
                <TableRow
                  key={submission.name}
                  onClick={() => openGrading(submission)}
                  className="cursor-pointer transition-colors hover:bg-muted"
                >
                  <TableCell className="font-medium">{submission.full_name}</TableCell>
                  <TableCell>{submission.assignment_title}</TableCell>
                  <TableCell>
                    {submission.submission_type ? (
                      <Badge variant="outline">{submission.submission_type}</Badge>
                    ) : (
                      <span className="text-muted-foreground">—</span>
                    )}
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {submission.submitted_at
                      ? formatDateTime(submission.submitted_at)
                      : "—"}
                  </TableCell>
                  <TableCell>
                    <GradeBadge submission={submission} />
                  </TableCell>
                  <TableCell className="text-right">
                    <Button
                      size="sm"
                      className="cursor-pointer transition-colors hover:bg-primary/90"
                      onClick={(event) => {
                        event.stopPropagation();
                        openGrading(submission);
                      }}
                    >
                      {submission.graded ? "Review" : "Grade"}
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

// dashboard/src/pages/FacultySubmissionsPage.vue
<template>
	<AppHeader title="Submissions" />

	<PageBody>
		<p class="mb-5 text-sm text-ink-gray-5">
			Open, run, and grade submissions from your cohort.
		</p>

		<DataTable
			:columns="columns"
			:rows="rows"
			:row-key="rowKey"
			:loading="submissions.loading && !submissions.data"
			:on-row-click="openGrading"
			empty="No submissions yet."
		>
			<template #cell-full_name="{ row }">
				<span class="truncate text-ink-gray-8">{{ row.full_name }}</span>
			</template>

			<template #cell-assignment_title="{ row }">
				<span class="truncate">{{ row.assignment_title }}</span>
			</template>

			<template #cell-submission_type="{ row }">
				<Badge
					v-if="row.submission_type"
					:label="row.submission_type"
					theme="gray"
					variant="subtle"
				/>
				<span v-else class="text-ink-gray-4">—</span>
			</template>

			<template #cell-submitted_at="{ row }">
				{{ formatDateTime(row.submitted_at) || '—' }}
			</template>

			<template #cell-grade="{ row }">
				<GradeBadge
					:graded="row.graded"
					:marks-obtained="row.marks_obtained"
					:grade="row.grade"
					:max-marks="row.max_marks"
				/>
			</template>

			<!-- The whole row opens the workspace; this is the affordance that
			     says so, and names what the grader is walking into. -->
			<template #cell-actions="{ row }">
				<Button :label="row.graded ? 'Review' : 'Grade'" @click.stop="openGrading(row)" />
			</template>
		</DataTable>
	</PageBody>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { Badge, Button, useCall } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import PageBody from '@/components/common/PageBody.vue'
import DataTable, { type Column } from '@/components/common/DataTable.vue'
import GradeBadge from '@/components/common/GradeBadge.vue'
import { formatDateTime } from '@/lib/dates'
import type { CohortSubmission } from '@/types'

const router = useRouter()

const columns: Column[] = [
	{ header: 'Student', key: 'full_name', variant: 'primary', width: '12rem' },
	{ header: 'Assignment', key: 'assignment_title' },
	{ header: 'Type', key: 'submission_type', width: '8rem' },
	{ header: 'Submitted', key: 'submitted_at', width: '11rem' },
	{ header: 'Grade', key: 'grade', width: '9rem' },
	{ header: '', key: 'actions', variant: 'actions', width: '7rem', align: 'right' },
]

const submissions = useCall<CohortSubmission[]>({
	url: '/api/v2/method/cs17_portal.api.list_cohort_submissions',
	method: 'GET',
	cacheKey: 'cohort-submissions',
})

const rows = computed(() => submissions.data ?? [])

const rowKey = (row: CohortSubmission) => row.name

function openGrading(row: CohortSubmission) {
	router.push(`/faculty/submissions/${row.name}`)
}
</script>
