// dashboard/src/faculty/FacultyAssignmentDetailPage.tsx
import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useFrappeGetCall } from "frappe-react-sdk";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import ResponsiveTable, { type Column } from "@/components/ui/ResponsiveTable";
import RichText from "@/components/ui/RichText";
import SubmissionPreviewDialog from "@/components/ui/SubmissionPreviewDialog";
import GradeSubmissionDialog from "@/faculty/GradeSubmissionDialog";
import type { GradeInfo } from "@/faculty/GradeSubmissionDialog";
import AssignSubmissionDialog from "@/faculty/AssignSubmissionDialog";
import BulkAssignBar from "@/faculty/BulkAssignBar";
import { formatDateTime } from "@/lib/dayjs";
import { useBreadcrumb } from "@/context/BreadcrumbContext";

interface Assignment {
  name: string;
  title: string;
  description?: string;
  due_date: string;
  cohort: string;
  submission_type?: string;
  assignment_type?: string;
  max_marks?: number;
  remarks?: string;
}

interface Submission {
  name: string;
  student: string;
  full_name?: string;
  submitted_at: string;
  submission_document?: string;
  submission_url?: string;
  grade?: GradeInfo | null;
  _assign?: string | null;
}

function parseAssignees(value?: string | null): string[] {
  if (!value) return [];
  try {
    return JSON.parse(value);
  } catch {
    return [];
  }
}

export default function FacultyAssignmentDetailPage() {
  const { assignmentId } = useParams<{ assignmentId: string }>();
  const navigate = useNavigate();
  const { setBreadcrumb } = useBreadcrumb();
  const [gradeTarget, setGradeTarget] = useState<Submission | null>(null);
  const [assignTarget, setAssignTarget] = useState<Submission | null>(null);
  const [preview, setPreview] = useState<Submission | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const { data, isLoading, mutate } = useFrappeGetCall<{
    message: { assignment: Assignment; submissions: Submission[] };
  }>("cs17_portal.api.get_assignment_submissions", { assignment: assignmentId });

  const assignment = data?.message.assignment;
  const submissions = data?.message.submissions ?? [];

  function toggle(name: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(name) ? next.delete(name) : next.add(name);
      return next;
    });
  }

  function toggleAll() {
    setSelected((prev) =>
      prev.size === submissions.length
        ? new Set()
        : new Set(submissions.map((s) => s.name)),
    );
  }

  function clearSelection() {
    setSelected(new Set());
    mutate();
  }

  useEffect(() => {
    if (!assignment) return;
    setBreadcrumb([
      { label: "Assignments", href: "/faculty/assignments" },
      { label: assignment.title },
    ]);
    return () => setBreadcrumb([]);
  }, [assignment?.title]);

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-1/2" />
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-3/4" />
      </div>
    );
  }

  if (!assignment) {
    return <p className="text-muted-foreground">Assignment not found.</p>;
  }

  const isGraded = assignment.assignment_type === "Graded";
  const isGradeScale = isGraded && assignment.remarks === "Grade";
  const evaluationType = isGraded ? assignment.remarks : "Non-graded";

  const selection = {
    header: (
      <input
        type="checkbox"
        className="h-4 w-4 rounded border-border align-middle"
        checked={submissions.length > 0 && selected.size === submissions.length}
        onChange={toggleAll}
        aria-label="Select all submissions"
      />
    ),
    cell: (submission: Submission) => (
      <input
        type="checkbox"
        className="h-4 w-4 rounded border-border align-middle"
        checked={selected.has(submission.name)}
        onChange={() => toggle(submission.name)}
        aria-label={`Select ${submission.full_name ?? submission.student}`}
      />
    ),
  };

  const columns: Column<Submission>[] = [
    {
      header: "Student",
      variant: "primary",
      cell: (s) => s.full_name ?? s.student,
    },
    {
      header: "Submitted",
      cellClassName: "text-sm text-muted-foreground",
      cell: (s) => formatDateTime(s.submitted_at),
    },
    {
      header: "Grade",
      cell: (s) => (
        <GradeCell
          grade={s.grade}
          isGradeScale={isGradeScale}
          isGraded={isGraded}
        />
      ),
    },
    {
      header: "",
      variant: "actions",
      cellClassName: "text-right",
      cell: (s) => (
        <div className="flex items-center justify-end gap-2">
          <Button size="sm" variant="ghost" onClick={() => setPreview(s)}>
            Preview
          </Button>
          <Button size="sm" variant="ghost" onClick={() => setAssignTarget(s)}>
            {parseAssignees(s._assign).length > 0 ? "Assigned" : "Assign"}
          </Button>
          {isGraded && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setGradeTarget(s)}
            >
              {s.grade ? "Edit Grade" : "Grade"}
            </Button>
          )}
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <button
        onClick={() => navigate("/faculty/assignments")}
        className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Assignments
      </button>

      <div className="flex flex-col md:flex-row gap-6">
        <div className="flex-1 min-w-0">
          <h1 className="text-2xl font-bold mb-4">{assignment.title}</h1>
          <RichText content={assignment.description} />
        </div>

        <div className="w-full md:w-64 shrink-0">
          <div className="border border-border rounded-xl p-4 space-y-3">
            <div>
              <p className="text-xs text-muted-foreground">Due</p>
              <p className="text-sm font-medium">
                {formatDateTime(assignment.due_date)}
              </p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Cohort</p>
              <p className="text-sm font-medium">{assignment.cohort}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Evaluation Type</p>
              <p className="text-sm font-medium">{evaluationType}</p>
            </div>
            {evaluationType === "Marks" && (
              <div>
                <p className="text-xs text-muted-foreground">Max Marks</p>
                <p className="text-sm font-medium">{assignment.max_marks}</p>
              </div>
            )}
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-lg font-semibold mb-3">
          Submissions ({submissions.length})
        </h2>
        {selected.size > 0 && (
          <BulkAssignBar
            submissions={[...selected]}
            onDone={clearSelection}
          />
        )}
        <div className="md:bg-background md:border md:border-border md:rounded-xl md:p-5">
          <ResponsiveTable
            columns={columns}
            rows={submissions}
            rowKey={(s) => s.name}
            selection={selection}
            empty="No submissions yet."
          />
        </div>
      </div>

      {preview && (
        <SubmissionPreviewDialog
          open={!!preview}
          onOpenChange={(open) => !open && setPreview(null)}
          title={`Submission: ${preview.full_name ?? preview.student}`}
          submissionType={assignment.submission_type}
          submission={preview.name}
          fileUrl={preview.submission_document || preview.submission_url}
        />
      )}

      {assignTarget && (
        <AssignSubmissionDialog
          open={!!assignTarget}
          onOpenChange={(open) => !open && setAssignTarget(null)}
          submission={(() => {
            const live =
              submissions.find((s) => s.name === assignTarget.name) ??
              assignTarget;
            return {
              name: live.name,
              full_name: live.full_name,
              assignedTo: parseAssignees(live._assign),
            };
          })()}
          onSuccess={mutate}
        />
      )}

      {gradeTarget && (
        <GradeSubmissionDialog
          open={!!gradeTarget}
          onOpenChange={(open) => !open && setGradeTarget(null)}
          submission={gradeTarget}
          evaluationType={assignment.remarks ?? "Marks"}
          maxMarks={assignment.max_marks}
          onSuccess={mutate}
        />
      )}
    </div>
  );
}

function GradeCell({
  grade,
  isGradeScale,
  isGraded,
}: {
  grade?: GradeInfo | null;
  isGradeScale: boolean;
  isGraded: boolean;
}) {
  if (!isGraded) return <span className="text-sm text-muted-foreground">—</span>;
  if (!grade) return <Badge variant="secondary">Ungraded</Badge>;
  const value = isGradeScale ? grade.grade : grade.marks_obtained;
  return (
    <div className="flex items-center gap-2">
      <span className="text-sm font-medium">{value ?? "—"}</span>
      {grade.is_published ? (
        <Badge>Published</Badge>
      ) : (
        <Badge variant="outline">Draft</Badge>
      )}
    </div>
  );
}

// dashboard/src/pages/FacultyAssignmentDetailPage.vue
<template>
	<AppHeader title="Assignment">
		<template #left-mobile>
			<PageHeaderBackButton to="/faculty/assignments" />
		</template>
	</AppHeader>

	<div class="px-3 py-5 pb-10 sm:px-5">
		<PageSkeleton v-if="detail.loading && !detail.data" />

		<EmptyState
			v-else-if="!assignment"
			icon="lucide-file-question"
			title="Assignment not found"
			description="It may have been deleted."
		>
			<template #action>
				<Button label="Back to assignments" route="/faculty/assignments" />
			</template>
		</EmptyState>

		<div v-else class="space-y-6">
			<div class="flex flex-col gap-6 md:flex-row">
				<div class="min-w-0 flex-1">
					<h1 class="mb-4 text-2xl text-ink-gray-9">{{ assignment.title }}</h1>
					<MarkdownText :content="assignment.description" />
				</div>

				<div class="w-full shrink-0 md:w-64">
					<dl
						class="space-y-3 rounded-4 border border-outline-gray-1 bg-surface-base p-4"
					>
						<div v-for="meta in metaRows" :key="meta.label">
							<dt class="text-xs text-ink-gray-5">{{ meta.label }}</dt>
							<dd class="text-base font-medium text-ink-gray-8">
								{{ meta.value }}
							</dd>
						</div>
					</dl>
				</div>
			</div>

			<section class="space-y-3">
				<h2 class="text-lg font-semibold text-ink-gray-8">
					Submissions ({{ submissions.length }})
				</h2>

				<BulkAssignBar
					v-if="selection.length"
					:submissions="selection"
					@done="clearSelection"
				/>

				<DataTable
					v-model:selection="selection"
					:columns="columns"
					:rows="submissions"
					:row-key="(row: CS17Submission) => row.name"
					selectable
					empty="No submissions yet."
				>
					<template #cell-student="{ row }">
						<span class="truncate text-ink-gray-8">{{
							row.full_name ?? row.student
						}}</span>
					</template>

					<template #cell-submitted="{ row }">
						<span class="text-ink-gray-6">{{ formatDateTime(row.submitted_at) }}</span>
					</template>

					<template #cell-grade="{ row }">
						<span v-if="!isGraded" class="text-ink-gray-5">—</span>
						<Badge
							v-else-if="!row.grade"
							label="Ungraded"
							theme="gray"
							variant="subtle"
						/>
						<span v-else class="flex items-center gap-2">
							<span class="text-base font-medium text-ink-gray-8">{{
								gradeValue(row.grade)
							}}</span>
							<Badge
								:label="row.grade.is_published ? 'Published' : 'Draft'"
								:theme="row.grade.is_published ? 'green' : 'amber'"
								variant="subtle"
							/>
						</span>
					</template>

					<template #cell-actions="{ row }">
						<div class="flex flex-wrap items-center gap-2 md:justify-end">
							<Button variant="ghost" label="Preview" @click="previewTarget = row" />
							<Button
								variant="ghost"
								:label="assigneesOf(row).length ? 'Assigned' : 'Assign'"
								@click="assignTargetName = row.name"
							/>
							<Button
								v-if="isGraded"
								variant="outline"
								:label="row.grade ? 'Edit grade' : 'Grade'"
								@click="gradeTarget = row"
							/>
						</div>
					</template>
				</DataTable>
			</section>
		</div>
	</div>

	<SubmissionPreviewDialog
		v-if="previewTarget"
		:open="Boolean(previewTarget)"
		:title="`Submission: ${previewTarget.full_name ?? previewTarget.student}`"
		:submission-type="assignment?.submission_type"
		:submission="previewTarget.name"
		:file-url="previewTarget.submission_document || previewTarget.submission_url"
		@update:open="previewTarget = null"
	/>

	<AssignSubmissionDialog
		v-if="assignTarget"
		:open="Boolean(assignTarget)"
		:submission="assignTarget"
		@update:open="assignTargetName = null"
		@success="detail.reload()"
	/>

	<GradeSubmissionDialog
		v-if="gradeTarget"
		:open="Boolean(gradeTarget)"
		:submission="gradeTarget"
		:evaluation-type="assignment?.remarks ?? 'Marks'"
		:max-marks="assignment?.max_marks"
		@update:open="gradeTarget = null"
		@success="detail.reload()"
	/>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { Badge, Button, PageHeaderBackButton, useCall } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import DataTable, { type Column } from '@/components/common/DataTable.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import MarkdownText from '@/components/common/MarkdownText.vue'
import PageSkeleton from '@/components/common/PageSkeleton.vue'
import SubmissionPreviewDialog from '@/components/assignments/SubmissionPreviewDialog.vue'
import AssignSubmissionDialog, {
	type AssignTarget,
} from '@/components/faculty/AssignSubmissionDialog.vue'
import BulkAssignBar from '@/components/faculty/BulkAssignBar.vue'
import GradeSubmissionDialog from '@/components/faculty/GradeSubmissionDialog.vue'
import { useBreadcrumbs } from '@/composables/useBreadcrumbs'
import { formatDateTime } from '@/lib/dates'
import type { CS17Assignment, CS17Grade, CS17Submission } from '@/types'

const route = useRoute()
const breadcrumbs = useBreadcrumbs()

const assignmentId = computed(() => String(route.params.assignmentId ?? ''))

const detail = useCall<
	{ assignment: CS17Assignment; submissions: CS17Submission[] },
	{ assignment: string }
>({
	url: '/api/v2/method/cs17_portal.api.get_assignment_submissions',
	params: () => ({ assignment: assignmentId.value }),
	refetch: true,
})

const assignment = computed(() => detail.data?.assignment ?? null)
const submissions = computed(() => detail.data?.submissions ?? [])

const selection = ref<string[]>([])
const previewTarget = ref<CS17Submission | null>(null)
const gradeTarget = ref<CS17Submission | null>(null)
/**
 * The assign dialog is addressed by name, not by row: it reloads the list after
 * every assign, and the chips have to follow the fresh `_assign`.
 */
const assignTargetName = ref<string | null>(null)

const isGraded = computed(() => assignment.value?.assignment_type === 'Graded')
const isGradeScale = computed(() => isGraded.value && assignment.value?.remarks === 'Grade')

const metaRows = computed(() => {
	const rows = [
		{ label: 'Due', value: formatDateTime(assignment.value?.due_date) },
		{ label: 'Cohort', value: assignment.value?.cohort ?? '—' },
		{
			label: 'Evaluation Type',
			value: isGraded.value ? (assignment.value?.remarks ?? '—') : 'Non-graded',
		},
	]
	if (isGraded.value && assignment.value?.remarks === 'Marks') {
		rows.push({ label: 'Max Marks', value: String(assignment.value?.max_marks ?? '—') })
	}
	return rows
})

const columns: Column[] = [
	{ header: 'Student', key: 'student', variant: 'primary' },
	{ header: 'Submitted', key: 'submitted', width: '11rem' },
	{ header: 'Grade', key: 'grade', width: '11rem' },
	{ header: '', key: 'actions', variant: 'actions', width: '16rem', align: 'right' },
]

/** `_assign` is Frappe's ToDo mirror: a JSON array of user ids, or nothing. */
function assigneesOf(submission: CS17Submission): string[] {
	if (!submission._assign) return []
	try {
		const parsed = JSON.parse(submission._assign)
		return Array.isArray(parsed) ? parsed : []
	} catch {
		return []
	}
}

const assignTarget = computed<AssignTarget | null>(() => {
	const row = submissions.value.find((s) => s.name === assignTargetName.value)
	if (!row) return null
	return { name: row.name, fullName: row.full_name, assignedTo: assigneesOf(row) }
})

function gradeValue(grade: CS17Grade): string {
	const value = isGradeScale.value ? grade.grade : grade.marks_obtained
	return value === null || value === undefined ? '—' : String(value)
}

function clearSelection() {
	selection.value = []
	detail.reload()
}

watch(
	() => assignment.value?.title,
	(title) => {
		if (!title) return
		breadcrumbs.set([{ label: 'Assignments', route: '/faculty/assignments' }, { label: title }])
	},
	{ immediate: true },
)
</script>
