// dashboard/src/faculty/FacultyAssignmentsPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useFrappeGetCall, useFrappeGetDocList } from "frappe-react-sdk";
import ResponsiveTable, { type Column } from "@/components/ui/ResponsiveTable";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Plus } from "lucide-react";
import { formatDateTime } from "@/lib/dayjs";
import CreateAssignmentSheet from "@/faculty/CreateAssignmentSheet";
import PublishAssignmentDialog from "@/faculty/PublishAssignmentDialog";
import DeleteAssignmentDialog from "@/faculty/DeleteAssignmentDialog";
import { Trash2, ChevronDown } from "lucide-react";

interface FacultyAssignment {
  name: string;
  title: string;
  cohort: string;
  submission_type: string;
  assignment_type: string;
  due_date: string;
  is_published: number;
  publish_on: string | null;
  submission_count: number;
}

const ALL_COHORTS = "all";

export default function FacultyAssignmentsPage() {
  const [cohortFilter, setCohortFilter] = useState(ALL_COHORTS);
  const [createOpen, setCreateOpen] = useState(false);
  const [editDraft, setEditDraft] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<FacultyAssignment | null>(
    null,
  );

  const { data: cohortDocs } = useFrappeGetDocList("CS17 Cohort", {
    fields: ["name"],
    limit: 0,
  });
  const cohorts = (cohortDocs ?? []).map((c) => c.name);

  const { data, isLoading, mutate } = useFrappeGetCall<{
    message: FacultyAssignment[];
  }>("cs17_portal.api.get_faculty_assignments", {
    cohort: cohortFilter === ALL_COHORTS ? undefined : cohortFilter,
  });

  const assignments = data?.message ?? [];
  const drafts = assignments.filter(
    (assignment) => !assignment.is_published && !assignment.publish_on,
  );

  function openNew() {
    setEditDraft(null);
    setCreateOpen(true);
  }

  function openDraft(name: string) {
    setEditDraft(name);
    setCreateOpen(true);
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Assignments</h1>
          <p className="text-sm text-muted-foreground mt-1">
            {assignments.length} total
          </p>
        </div>
        <Button onClick={openNew}>
          <Plus className="w-4 h-4 mr-1.5" />
          New Assignment
        </Button>
      </div>

      {drafts.length > 0 && (
        <DraftsSection drafts={drafts} onOpen={openDraft} />
      )}

      <div className="flex items-center gap-3">
        <Select value={cohortFilter} onValueChange={setCohortFilter}>
          <SelectTrigger className="w-56">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL_COHORTS}>All cohorts</SelectItem>
            {cohorts.map((cohort) => (
              <SelectItem key={cohort} value={cohort}>
                {cohort}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:bg-background md:border md:border-border md:rounded-xl md:p-5">
        {isLoading ? (
          <div className="space-y-2">
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
          </div>
        ) : (
          <AssignmentTable
            assignments={assignments}
            onChange={mutate}
            onDelete={setDeleteTarget}
          />
        )}
      </div>

      <CreateAssignmentSheet
        open={createOpen}
        onOpenChange={(open) => {
          setCreateOpen(open);
          if (!open) setEditDraft(null);
        }}
        cohorts={cohorts}
        onCreated={mutate}
        draftName={editDraft}
      />

      {deleteTarget && (
        <DeleteAssignmentDialog
          open={!!deleteTarget}
          onOpenChange={(open) => !open && setDeleteTarget(null)}
          assignment={deleteTarget}
          onSuccess={mutate}
        />
      )}
    </div>
  );
}

function DraftsSection({
  drafts,
  onOpen,
}: {
  drafts: FacultyAssignment[];
  onOpen: (name: string) => void;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div>
      <Button
        variant="outline"
        size="sm"
        onClick={() => setOpen((prev) => !prev)}
      >
        Drafts ({drafts.length})
        <ChevronDown
          className={`w-4 h-4 ml-1 transition-transform ${open ? "rotate-180" : ""}`}
        />
      </Button>
      {open && (
        <div className="mt-3 flex flex-wrap gap-2">
          {drafts.map((draft) => (
            <button
              key={draft.name}
              onClick={() => onOpen(draft.name)}
              className="text-sm border border-border rounded-lg px-3 py-1.5 hover:bg-muted/50 transition-colors"
            >
              {draft.title || "Untitled"}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function AssignmentTable({
  assignments,
  onChange,
  onDelete,
}: {
  assignments: FacultyAssignment[];
  onChange: () => void;
  onDelete: (assignment: FacultyAssignment) => void;
}) {
  const navigate = useNavigate();
  const [publishTarget, setPublishTarget] = useState<FacultyAssignment | null>(
    null,
  );

  const columns: Column<FacultyAssignment>[] = [
    {
      header: "Title",
      variant: "primary",
      cell: (a) => (
        <button
          className="text-left hover:underline"
          onClick={() => navigate(`/faculty/assignments/${a.name}`)}
        >
          {a.title}
        </button>
      ),
    },
    {
      header: "Cohort",
      cellClassName: "text-sm text-muted-foreground",
      cell: (a) => a.cohort,
    },
    {
      header: "Type",
      cell: (a) => <Badge variant="secondary">{a.submission_type}</Badge>,
    },
    {
      header: "Due",
      cellClassName: "text-sm text-muted-foreground",
      cell: (a) => formatDateTime(a.due_date),
    },
    {
      header: "Submissions",
      cell: (a) => <Badge variant="outline">{a.submission_count}</Badge>,
    },
    {
      header: "Status",
      cell: (a) => <StatusBadge assignment={a} />,
    },
    {
      header: "",
      variant: "actions",
      cellClassName: "text-right",
      cell: (a) => (
        <div className="flex items-center justify-end gap-2">
          {!a.is_published && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setPublishTarget(a)}
            >
              {a.publish_on ? "Reschedule" : "Publish"}
            </Button>
          )}
          <Button
            size="sm"
            variant="ghost"
            aria-label={`Delete ${a.title}`}
            onClick={() => onDelete(a)}
          >
            <Trash2 className="w-4 h-4 text-muted-foreground" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <>
      <ResponsiveTable
        columns={columns}
        rows={assignments}
        rowKey={(a) => a.name}
        empty="No assignments yet."
      />

      {publishTarget && (
        <PublishAssignmentDialog
          open={!!publishTarget}
          onOpenChange={(open) => !open && setPublishTarget(null)}
          assignment={publishTarget}
          onSuccess={onChange}
        />
      )}
    </>
  );
}

function StatusBadge({ assignment }: { assignment: FacultyAssignment }) {
  if (assignment.is_published) return <Badge>Published</Badge>;
  if (assignment.publish_on)
    return (
      <div className="flex flex-col items-start gap-1">
        <Badge variant="secondary">Scheduled</Badge>
        <span className="text-xs text-muted-foreground">
          {formatDateTime(assignment.publish_on)}
        </span>
      </div>
    );
  return <Badge variant="outline">Draft</Badge>;
}

// dashboard/src/pages/FacultyAssignmentsPage.vue
<template>
	<AppHeader title="Assignments">
		<template #actions>
			<Button
				variant="solid"
				theme="gray"
				icon-left="lucide-plus"
				label="New Assignment"
				@click="openNew"
			/>
		</template>
	</AppHeader>

	<div class="space-y-5 px-3 py-5 pb-10 sm:px-5">
		<div>
			<h1 class="text-2xl font-semibold text-ink-gray-9">Assignments</h1>
			<p class="mt-1 text-p-base text-ink-gray-5">{{ rows.length }} total</p>
		</div>

		<!-- Drafts are invisible to students, so they sit above the table as a
		     collapsed row rather than competing with published work in it. -->
		<div v-if="drafts.length">
			<Button
				:label="`Drafts (${drafts.length})`"
				:icon-right="draftsOpen ? 'lucide-chevron-up' : 'lucide-chevron-down'"
				:aria-expanded="draftsOpen"
				@click="draftsOpen = !draftsOpen"
			/>
			<div v-if="draftsOpen" class="mt-3 flex flex-wrap gap-2">
				<button
					v-for="draft in drafts"
					:key="draft.name"
					type="button"
					class="rounded-4 border border-outline-gray-2 px-3 py-1.5 text-base text-ink-gray-7 hover:bg-surface-gray-2"
					@click="openDraft(draft.name)"
				>
					{{ draft.title || 'Untitled' }}
				</button>
			</div>
		</div>

		<div class="max-w-xs">
			<Select
				label="Cohort"
				:model-value="cohortFilter"
				:options="cohortFilterOptions"
				@update:model-value="cohortFilter = String($event)"
			/>
		</div>

		<div class="md:rounded-4 md:border md:border-outline-gray-1 md:bg-surface-base md:p-5">
			<DataTable
				:columns="columns"
				:rows="rows"
				:row-key="(row: AssignmentRow) => row.name"
				:loading="assignmentsCall.loading && !assignmentsCall.data"
				empty="No assignments yet."
			>
				<template #cell-title="{ row }">
					<button
						type="button"
						class="truncate text-left text-ink-gray-8 hover:underline"
						@click="router.push(`/faculty/assignments/${row.name}`)"
					>
						{{ row.title }}
					</button>
				</template>

				<template #cell-cohort="{ row }">
					<span class="text-ink-gray-6">{{ row.cohort }}</span>
				</template>

				<template #cell-submission_type="{ row }">
					<Badge :label="row.submission_type" theme="gray" variant="subtle" />
				</template>

				<template #cell-due_date="{ row }">
					<span class="text-ink-gray-6">{{ formatDateTime(row.due_date) }}</span>
				</template>

				<template #cell-submission_count="{ row }">
					<Badge
						:label="String(row.submission_count ?? 0)"
						theme="gray"
						variant="outline"
					/>
				</template>

				<template #cell-status="{ row }">
					<div class="flex flex-col items-start gap-0.5">
						<Badge :label="row.statusLabel" :theme="row.statusTheme" variant="subtle" />
						<span v-if="row.scheduledAt" class="text-xs text-ink-gray-5">
							{{ row.scheduledAt }}
						</span>
					</div>
				</template>

				<template #cell-actions="{ row }">
					<div class="flex items-center justify-end gap-2">
						<Button
							v-if="!row.is_published"
							:label="row.publish_on ? 'Reschedule' : 'Publish'"
							@click="publishTarget = row"
						/>
						<Button
							variant="ghost"
							icon="lucide-trash-2"
							:aria-label="`Delete ${row.title}`"
							@click="deleteTarget = row"
						/>
					</div>
				</template>
			</DataTable>
		</div>
	</div>

	<AssignmentFormDialog
		v-model:open="formOpen"
		:cohorts="cohorts"
		:draft-name="editingDraft"
		@saved="assignmentsCall.reload()"
	/>

	<PublishAssignmentDialog
		:open="Boolean(publishTarget)"
		:assignment="publishTarget"
		@update:open="onPublishOpen"
		@success="assignmentsCall.reload()"
	/>

	<DeleteAssignmentDialog
		:open="Boolean(deleteTarget)"
		:assignment="deleteTarget"
		@update:open="onDeleteOpen"
		@success="assignmentsCall.reload()"
	/>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Badge, Button, Select, useCall, useList } from 'frappe-ui'
import DataTable, { type Column } from '@/components/common/DataTable.vue'
import AssignmentFormDialog from '@/components/faculty/AssignmentFormDialog.vue'
import DeleteAssignmentDialog from '@/components/faculty/DeleteAssignmentDialog.vue'
import PublishAssignmentDialog from '@/components/faculty/PublishAssignmentDialog.vue'
import AppHeader from '@/components/shell/AppHeader.vue'
import { formatDateTime } from '@/lib/dates'
import type { CS17Assignment } from '@/types'

/** A row plus the badge ladder, resolved once instead of three times in the cell. */
interface AssignmentRow extends CS17Assignment {
	statusLabel: 'Published' | 'Scheduled' | 'Draft'
	statusTheme: 'green' | 'amber' | 'gray'
	/** The scheduled publish time, shown under the Scheduled badge. */
	scheduledAt: string
}

const ALL_COHORTS = 'all'

const columns: Column[] = [
	{ header: 'Title', key: 'title', variant: 'primary' },
	{ header: 'Cohort', key: 'cohort', width: '8rem' },
	{ header: 'Type', key: 'submission_type', width: '7rem' },
	{ header: 'Due', key: 'due_date', width: '10rem' },
	{ header: 'Submissions', key: 'submission_count', width: '7rem' },
	{ header: 'Status', key: 'status', width: '9rem' },
	{ header: '', key: 'actions', variant: 'actions', width: '12rem', align: 'right' },
]

const router = useRouter()

const cohortFilter = ref(ALL_COHORTS)
const draftsOpen = ref(false)
const formOpen = ref(false)
const editingDraft = ref<string | null>(null)
const publishTarget = ref<AssignmentRow | null>(null)
const deleteTarget = ref<AssignmentRow | null>(null)

const cohortList = useList<{ name: string }>({
	doctype: 'CS17 Cohort',
	fields: ['name'],
	orderBy: 'name asc',
	limit: 500,
})

const assignmentsCall = useCall<CS17Assignment[], { cohort?: string }>({
	url: '/api/v2/method/cs17_portal.api.get_faculty_assignments',
	method: 'GET',
	params: () => (cohortFilter.value === ALL_COHORTS ? {} : { cohort: cohortFilter.value }),
	refetch: true,
})

const cohorts = computed(() => (cohortList.data ?? []).map((cohort) => cohort.name))

const cohortFilterOptions = computed(() => [
	{ label: 'All cohorts', value: ALL_COHORTS },
	...cohorts.value.map((cohort) => ({ label: cohort, value: cohort })),
])

const rows = computed<AssignmentRow[]>(() =>
	(assignmentsCall.data ?? []).map((assignment) => ({ ...assignment, ...status(assignment) })),
)

/** Neither published nor scheduled — the rows the Drafts row offers to reopen. */
const drafts = computed(() => rows.value.filter((row) => row.statusLabel === 'Draft'))

function onPublishOpen(open: boolean) {
	if (!open) publishTarget.value = null
}

function onDeleteOpen(open: boolean) {
	if (!open) deleteTarget.value = null
}

function status(assignment: CS17Assignment) {
	if (assignment.is_published) {
		return { statusLabel: 'Published', statusTheme: 'green', scheduledAt: '' } as const
	}
	if (assignment.publish_on) {
		return {
			statusLabel: 'Scheduled',
			statusTheme: 'amber',
			scheduledAt: formatDateTime(assignment.publish_on),
		} as const
	}
	return { statusLabel: 'Draft', statusTheme: 'gray', scheduledAt: '' } as const
}

function openNew() {
	editingDraft.value = null
	formOpen.value = true
}

function openDraft(name: string) {
	editingDraft.value = name
	formOpen.value = true
}

// Reopening "New Assignment" after editing a draft must not carry the draft
// name over, and only the close path can clear it.
watch(formOpen, (open) => {
	if (!open) editingDraft.value = null
})
</script>
