// dashboard/src/pages/ProjectsPage.vue
<template>
	<AppHeader title="Projects" />

	<div class="px-3 py-5 pb-10 sm:px-5">
		<div class="mx-auto max-w-[940px] space-y-5">
			<div class="flex items-start justify-between gap-3">
				<div class="min-w-0">
					<h1 class="text-2xl text-ink-gray-9">Projects</h1>
					<p v-if="!loading" class="mt-1.5 text-sm text-ink-gray-5">{{ countLabel }}</p>
				</div>
				<Button
					variant="solid"
					theme="gray"
					icon-left="lucide-plus"
					label="New project"
					:loading="createProject.loading"
					@click="promptForNewProject"
				/>
			</div>

			<div v-if="loading" class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
				<Skeleton v-for="n in 3" :key="n" class="h-56 rounded-4" />
			</div>

			<EmptyState
				v-else-if="!projects.length"
				icon="lucide-blocks"
				title="No projects yet"
				description="Create your first Scratch project to get started."
			>
				<template #action>
					<Button
						variant="solid"
						theme="gray"
						icon-left="lucide-plus"
						label="New project"
						:loading="createProject.loading"
						@click="promptForNewProject"
					/>
				</template>
			</EmptyState>

			<div v-else class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
				<ProjectCard v-for="project in projects" :key="project.name" :project="project" />
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { Button, Skeleton, dialog, useCall } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import ProjectCard from '@/components/projects/ProjectCard.vue'
import { frappeErrorMessage } from '@/lib/frappeError'
import type { CS17Project } from '@/types'

const router = useRouter()

const projectList = useCall<CS17Project[]>({
	url: '/api/v2/method/cs17_portal.api.list_my_projects',
})

const createProject = useCall<{ name: string }, { project_title: string }>({
	url: '/api/v2/method/cs17_portal.api.create_project',
	method: 'POST',
	immediate: false,
})

const projects = computed(() => projectList.data ?? [])
const loading = computed(() => projectList.loading && !projectList.data)
const countLabel = computed(
	() => `${projects.value.length} project${projects.value.length === 1 ? '' : 's'}`,
)

/**
 * The name is asked for up front because a Scratch project is only ever
 * opened from this grid — an untitled card is unfindable a week later.
 */
function promptForNewProject() {
	dialog.prompt({
		title: 'New project',
		fields: [
			{
				name: 'project_title',
				label: 'Project name',
				placeholder: 'Maze game',
				required: true,
			},
		],
		confirmLabel: 'Create',
		onConfirm: async ({ values }) => {
			const title = String(values.project_title ?? '').trim()
			if (!title) throw new Error('Give the project a name.')

			// `submit()` resolves rather than throwing, so the error ref is what
			// says whether this call landed.
			const created = await createProject.submit({ project_title: title })
			if (createProject.error || !created) {
				throw new Error(
					frappeErrorMessage(createProject.error, 'Could not create the project.'),
				)
			}

			// The grid refreshes behind us; we leave for the editor either way.
			projectList.reload()
			router.push(`/projects/${created.name}/edit`)
		},
	})
}
</script>

// dashboard/src/pages/ProjectsPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useFrappeGetCall, useFrappePostCall } from "frappe-react-sdk";
import { Blocks, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDateTime } from "@/lib/dayjs";

interface Project {
	name: string;
	project_title: string;
	thumbnail: string | null;
	last_saved_at: string | null;
}

export default function ProjectsPage() {
	const navigate = useNavigate();

	const {
		data,
		isLoading,
		mutate,
	} = useFrappeGetCall<{ message: Project[] }>("cs17_portal.api.list_my_projects");

	const { call: createProject, loading: creating } = useFrappePostCall(
		"cs17_portal.api.create_project",
	);

	const [error, setError] = useState<string | null>(null);

	async function handleNewProject() {
		const projectTitle = window.prompt("Name your project")?.trim();
		if (!projectTitle) return;
		setError(null);
		try {
			const response = await createProject({ project_title: projectTitle });
			await mutate();
			navigate(`/projects/${response.message.name}/edit`);
		} catch (err) {
			setError((err as { message?: string })?.message ?? "Could not create the project.");
		}
	}

	const projects = data?.message ?? [];

	return (
		<div className="space-y-6">
			<div className="flex items-center justify-between">
				<div>
					<h1 className="text-2xl font-bold">Projects</h1>
					<p className="text-sm text-muted-foreground mt-1">
						{projects.length} project{projects.length === 1 ? "" : "s"}
					</p>
				</div>
				<Button onClick={handleNewProject} disabled={creating}>
					<Plus className="w-4 h-4" />
					{creating ? "Creating…" : "New Project"}
				</Button>
			</div>

			{error && <p className="text-sm text-destructive">{error}</p>}

			{isLoading ? (
				<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
					<Skeleton className="h-40 w-full" />
					<Skeleton className="h-40 w-full" />
					<Skeleton className="h-40 w-full" />
				</div>
			) : projects.length === 0 ? (
				<div className="border border-dashed border-border rounded-xl p-12 text-center">
					<Blocks className="w-8 h-8 mx-auto text-muted-foreground" />
					<p className="mt-3 text-sm text-muted-foreground">
						No projects yet. Create your first Scratch project to get started.
					</p>
				</div>
			) : (
				<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
					{projects.map((project) => (
						<Card
							key={project.name}
							className="cursor-pointer transition-colors hover:border-primary py-0 overflow-hidden"
							onClick={() => navigate(`/projects/${project.name}/edit`)}
						>
							<div className="aspect-[4/3] bg-muted flex items-center justify-center overflow-hidden">
								{project.thumbnail ? (
									<img
										src={project.thumbnail}
										alt={project.project_title}
										className="w-full h-full object-cover"
									/>
								) : (
									<Blocks className="w-8 h-8 text-muted-foreground" />
								)}
							</div>
							<CardContent className="p-4">
								<p className="font-medium truncate">{project.project_title}</p>
								<p className="text-xs text-muted-foreground mt-1">
									{project.last_saved_at
										? `Saved ${formatDateTime(project.last_saved_at)}`
										: "Not saved yet"}
								</p>
							</CardContent>
						</Card>
					))}
				</div>
			)}
		</div>
	);
}
