// dashboard/src/faculty/AssignmentPreview.tsx
import { Button } from "@/components/ui/button";
import RichText from "@/components/ui/RichText";
import { formatDateTime } from "@/lib/dayjs";

export interface AssignmentDraft {
  title: string;
  cohort: string;
  submission_type: string;
  assignment_type: string;
  max_marks: string;
  remarks: string;
  due_date: string;
  description: string;
}

interface Props {
  draft: AssignmentDraft;
}

// Renders a draft exactly as a student sees it on AssignmentDetailPage.
export default function AssignmentPreview({ draft }: Props) {
  const evaluationType =
    draft.assignment_type === "Graded" ? draft.remarks : "Non-graded";

  return (
    <div className="flex flex-col md:flex-row gap-6">
      <div className="flex-1 min-w-0">
        <h1 className="text-2xl font-bold mb-4">
          {draft.title || "Untitled Assignment"}
        </h1>
        <RichText content={draft.description} />
      </div>

      <div className="md:w-56 shrink-0">
        <div className="border border-border rounded-xl p-4 space-y-3">
          <Meta label="Due" value={draft.due_date ? formatDateTime(draft.due_date) : "—"} />
          <Meta label="Evaluation Type" value={evaluationType} />
          {evaluationType === "Marks" && (
            <Meta label="Max Marks" value={draft.max_marks || "—"} />
          )}
          <Button variant="outline" className="w-full" disabled>
            Submit Assignment
          </Button>
        </div>
      </div>
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-sm font-medium">{value}</p>
    </div>
  );
}

// dashboard/src/components/faculty/AssignmentPreview.vue
<template>
	<!-- The same two-column shape the student sees on AssignmentDetailPage, so
	     the author is looking at the real thing and not an approximation. -->
	<div class="flex flex-col gap-6 md:flex-row">
		<div class="min-w-0 flex-1">
			<h2 class="mb-4 text-2xl font-semibold text-ink-gray-9">
				{{ draft.title || 'Untitled Assignment' }}
			</h2>
			<MarkdownText :content="draft.description" />
		</div>

		<div class="shrink-0 md:w-56">
			<div class="space-y-3 rounded-4 border border-outline-gray-1 p-4">
				<div v-for="row in metaRows" :key="row.label">
					<p class="text-xs text-ink-gray-5">{{ row.label }}</p>
					<p class="text-base font-medium text-ink-gray-8">{{ row.value }}</p>
				</div>
				<Button class="w-full" label="Submit Assignment" variant="outline" disabled />
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Button } from 'frappe-ui'
import MarkdownText from '@/components/common/MarkdownText.vue'
import { formatDateTime } from '@/lib/dates'
import type { AssignmentType, EvaluationType, SubmissionType } from '@/types'

/**
 * The authoring form's working copy of an assignment. Every field is a string
 * because it is bound straight to an input; the numbers and datetimes are
 * coerced on the way to the API, not on the way in.
 */
export interface AssignmentDraft {
	title: string
	cohort: string
	submission_type: SubmissionType
	assignment_type: AssignmentType
	max_marks: string
	/** The doctype's name for the evaluation scale: `Grade` or `Marks`. */
	remarks: EvaluationType | ''
	/** A Frappe datetime, "YYYY-MM-DD HH:mm:ss". */
	due_date: string
	description: string
}

const props = defineProps<{ draft: AssignmentDraft }>()

const evaluationType = computed(() =>
	props.draft.assignment_type === 'Graded' ? props.draft.remarks : 'Non-graded',
)

const metaRows = computed(() => {
	const rows = [
		{ label: 'Due', value: formatDateTime(props.draft.due_date) || '—' },
		{ label: 'Evaluation Type', value: evaluationType.value || '—' },
	]
	if (evaluationType.value === 'Marks') {
		rows.push({ label: 'Max Marks', value: props.draft.max_marks || '—' })
	}
	return rows
})
</script>
