// dashboard/src/components/faculty/BulkAssignBar.vue
<template>
	<div
		class="flex flex-col gap-3 rounded-4 border border-outline-gray-1 bg-surface-gray-1 px-4 py-3 sm:flex-row sm:items-end"
	>
		<p class="text-base font-medium text-ink-gray-7 sm:pb-2">
			{{ submissions.length }} selected
		</p>

		<div class="sm:w-56">
			<FacultySelect
				v-model="assignTo"
				label="Assign selected to"
				placeholder="Pick a faculty member"
				:error="fieldError"
			/>
		</div>

		<Button
			class="sm:mb-0.5"
			variant="solid"
			theme="gray"
			label="Assign"
			:loading="assign.loading"
			@click="handleAssign"
		/>
	</div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button, toast, useCall } from 'frappe-ui'
import FacultySelect from '@/components/faculty/FacultySelect.vue'
import { frappeErrorMessage } from '@/lib/frappeError'

const props = defineProps<{
	/** The selected submission names. */
	submissions: string[]
}>()

const emit = defineEmits<{ done: [] }>()

const assignTo = ref('')
const fieldError = ref('')

const assign = useCall<null, { submissions: string[]; assign_to: string }>({
	url: '/api/v2/method/cs17_portal.api.assign_submissions',
	method: 'POST',
	immediate: false,
})

watch(assignTo, () => {
	fieldError.value = ''
})

async function handleAssign() {
	if (!assignTo.value) {
		fieldError.value = 'Pick a faculty member.'
		return
	}

	await assign.submit({ submissions: props.submissions, assign_to: assignTo.value })
	if (assign.error) {
		toast.error(frappeErrorMessage(assign.error, 'Could not assign the submissions.'))
		return
	}
	toast.success(`Assigned ${props.submissions.length} submissions.`)
	assignTo.value = ''
	emit('done')
}
</script>

// dashboard-react/src/faculty/BulkAssignBar.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import FacultySelect from "@/faculty/FacultySelect";
import { useFrappePostCall } from "frappe-react-sdk";

interface Props {
  submissions: string[];
  onDone: () => void;
}

export default function BulkAssignBar({ submissions, onDone }: Props) {
  const [assignTo, setAssignTo] = useState("");
  const [error, setError] = useState<string | null>(null);

  const { call, loading } = useFrappePostCall(
    "cs17_portal.api.assign_submissions",
  );

  async function handleAssign() {
    setError(null);
    if (!assignTo) {
      setError("Pick a faculty member.");
      return;
    }
    try {
      await call({ submissions, assign_to: assignTo });
      setAssignTo("");
      onDone();
    } catch (err: any) {
      setError(err?.message ?? "Could not assign the submissions.");
    }
  }

  return (
    <div className="flex items-center gap-3 mb-3 rounded-lg border border-border bg-muted/40 px-4 py-2">
      <span className="text-sm font-medium">
        {submissions.length} selected
      </span>
      <div className="w-56">
        <FacultySelect
          value={assignTo}
          onChange={setAssignTo}
          placeholder="Assign selected to…"
        />
      </div>
      <Button size="sm" onClick={handleAssign} disabled={loading}>
        {loading ? "Assigning…" : "Assign"}
      </Button>
      {error && <span className="text-sm text-destructive">{error}</span>}
    </div>
  );
}
