// dashboard/src/components/assignments/GradeDialog.vue
<template>
	<Dialog :open="open" title="Grade & Feedback" @update:open="emit('update:open', $event)">
		<div v-if="grade" class="space-y-3">
			<div v-if="!isLetterGrade && grade.grade">
				<p class="text-xs text-ink-gray-5">Grade</p>
				<p class="text-2xl text-ink-gray-9">{{ grade.grade }}</p>
			</div>
			<div>
				<p class="text-xs text-ink-gray-5">
					{{ isLetterGrade ? 'Grade' : 'Marks Obtained' }}
				</p>
				<p class="text-2xl text-ink-gray-9">{{ score }}</p>
			</div>
			<div v-if="grade.remarks">
				<p class="text-xs text-ink-gray-5">Remarks</p>
				<MarkdownText class="mt-0.5" :content="grade.remarks" />
			</div>
		</div>
		<p v-else class="text-p-base text-ink-gray-5">No grade posted yet.</p>
	</Dialog>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Dialog } from 'frappe-ui'
import MarkdownText from '@/components/common/MarkdownText.vue'
import type { CS17Grade } from '@/types'

const props = defineProps<{
	open: boolean
	/** The grade for the assignment the student picked, if one is published. */
	grade?: CS17Grade | null
}>()

const emit = defineEmits<{ 'update:open': [value: boolean] }>()

const isLetterGrade = computed(() => props.grade?.evaluation_type === 'Grade')

const score = computed(() => {
	if (!props.grade) return '—'
	const value = isLetterGrade.value ? props.grade.grade : props.grade.marks_obtained
	return value === null || value === undefined ? '—' : String(value)
})
</script>

// dashboard/src/components/ui/GradeDialog.tsx
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface Grade {
  evaluation_type?: string;
  grade?: string;
  marks_obtained?: number;
  remarks?: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  grade: Grade | null | undefined;
}

export default function GradeDialog({ open, onOpenChange, grade }: Props) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Grade & Feedback</DialogTitle>
        </DialogHeader>
        {grade ? (
          <div className="space-y-3 py-2">
            {grade.evaluation_type === "Grade" ? (
              <div>
                <p className="text-sm text-muted-foreground">Grade</p>
                <p className="text-2xl font-semibold">{grade.grade ?? "—"}</p>
              </div>
            ) : (
              <div>
                <p className="text-sm text-muted-foreground">Marks Obtained</p>
                <p className="text-2xl font-semibold">{grade.marks_obtained ?? "—"}</p>
              </div>
            )}
            {grade.remarks && (
              <div>
                <p className="text-sm text-muted-foreground">Remarks</p>
                <p className="text-sm">{grade.remarks}</p>
              </div>
            )}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground py-2">No grade posted yet.</p>
        )}
      </DialogContent>
    </Dialog>
  );
}
