// dashboard/src/pages/FacultyDashboardPage.vue
<template>
	<AppHeader title="Dashboard" />

	<PageBody width="narrow" class="space-y-6">
		<div>
			<h1 class="text-2xl text-ink-gray-9">Welcome back, {{ firstName }}.</h1>
			<p class="mt-1 text-sm text-ink-gray-5">{{ today }}</p>
		</div>

		<section class="space-y-4 rounded-4 border border-outline-gray-1 bg-surface-base p-5">
			<h2 class="text-lg-semibold text-ink-gray-8">Assigned to you</h2>

			<div v-if="assignedCall.loading && !assignedCall.data" class="cs17-delay-in space-y-3">
				<Skeleton v-for="n in 3" :key="n" class="h-8 w-full rounded-4" />
			</div>

			<p v-else-if="!assigned.length" class="text-p-sm text-ink-gray-5">
				No submissions assigned to you yet.
			</p>

			<div v-else class="divide-y divide-outline-gray-1">
				<RouterLink
					v-for="submission in assigned"
					:key="submission.name"
					:to="`/faculty/assignments/${submission.assignment}`"
					class="-mx-2 flex items-center justify-between gap-4 rounded-4 px-2 py-3 hover:bg-surface-gray-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-outline-gray-3"
				>
					<div class="min-w-0">
						<p class="truncate text-base text-ink-gray-8">{{ submission.full_name }}</p>
						<p class="mt-1 truncate text-sm text-ink-gray-5">
							{{ submission.assignment_title }}
						</p>
					</div>
					<span
						class="shrink-0 text-sm"
						:class="submission.grade ? 'text-ink-gray-5' : 'text-ink-gray-8'"
					>
						{{ submission.grade ? 'Graded' : 'Needs grading' }}
					</span>
				</RouterLink>
			</div>
		</section>
	</PageBody>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { Skeleton, useCall } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import PageBody from '@/components/common/PageBody.vue'
import { useSession } from '@/composables/useSession'
import { formatLongDate } from '@/lib/dates'
import type { CS17Submission } from '@/types'

const { profile } = useSession()

const firstName = computed(() => profile.value?.full_name?.split(' ')[0] ?? 'Faculty')
const today = formatLongDate()

const assignedCall = useCall<CS17Submission[], { limit: number }>({
	url: '/api/v2/method/cs17_portal.api.get_assigned_submissions',
	params: { limit: 5 },
})

const assigned = computed(() => assignedCall.data ?? [])
</script>

// dashboard/src/faculty/FacultyDashboardPage.tsx
import { useFrappeGetCall, useFrappeGetDocCount } from "frappe-react-sdk";
import { useCurrentProfile } from "@/hooks/useCurrentProfile";
import { Skeleton } from "@/components/ui/skeleton";
import { Link } from "react-router-dom";
import { formatDateTime } from "@/lib/dayjs";

interface RecentSubmission {
  name: string;
  student: string;
  full_name: string;
  assignment: string;
  assignment_title: string;
  submitted_at: string;
}

export default function FacultyDashboardPage() {
  const { profile } = useCurrentProfile();

  const { data: recentSubmissions, isLoading: submissionsLoading } =
    useFrappeGetCall<{ message: RecentSubmission[] }>(
      "cs17_portal.api.get_recent_submissions",
      profile ? { limit: 5 } : undefined,
      profile ? undefined : null,
    );

  const { data: publishedCount } = useFrappeGetDocCount(
    "CS17 Assignment",
    [["is_published", "=", 1]],
  );

  const { data: totalSubmissions } = useFrappeGetDocCount(
    "CS17 Assignment Submission",
  );

  const { data: gradedCount } = useFrappeGetDocCount(
    "CS17 Assignment Grade",
    [["submission", "!=", ""]],
  );

  const pendingCount =
    totalSubmissions != null && gradedCount != null
      ? Math.max(0, totalSubmissions - gradedCount)
      : null;

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    day: "numeric",
    month: "long",
  });

  const submissions: RecentSubmission[] = recentSubmissions?.message ?? [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">
          Welcome back, {profile?.full_name?.split(" ")[0] ?? "Faculty"}.
        </h1>
        <p className="text-sm text-muted-foreground mt-1">{today}</p>
      </div>

      <div className="flex gap-3 flex-wrap">
        <StatChip
          label="Published Assignments"
          value={publishedCount ?? null}
        />
        <StatChip
          label="Pending Submissions"
          value={pendingCount}
        />
      </div>

      <div className="bg-background border border-border rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold">Latest submissions</h3>
          <Link
            to="/faculty/assignments"
            className="text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            View all →
          </Link>
        </div>

        {submissionsLoading ? (
          <div className="space-y-3">
            {[0, 1, 2].map((i) => (
              <Skeleton key={i} className="h-10 w-full" />
            ))}
          </div>
        ) : submissions.length === 0 ? (
          <p className="text-xs text-muted-foreground">No submissions yet.</p>
        ) : (
          <div className="divide-y divide-border">
            {submissions.map((submission) => (
              <div
                key={submission.name}
                className="py-3 flex items-center justify-between gap-4"
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium truncate">
                    {submission.full_name}
                  </p>
                  <p className="text-xs text-muted-foreground truncate">
                    {submission.assignment_title}
                  </p>
                </div>
                <p className="text-xs text-muted-foreground shrink-0">
                  {submission.submitted_at
                    ? formatDateTime(submission.submitted_at)
                    : "—"}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function StatChip({ label, value }: { label: string; value: number | null }) {
  return (
    <div className="bg-background border border-border rounded-xl px-5 py-4 min-w-[160px]">
      {value === null ? (
        <Skeleton className="h-8 w-12 mb-1" />
      ) : (
        <p className="text-2xl font-bold">{value}</p>
      )}
      <p className="text-xs text-muted-foreground mt-1">{label}</p>
    </div>
  );
}
