// dashboard/src/pages/FacultyAnnouncementsPage.vue
<template>
	<AppHeader title="Announcements">
		<template #actions>
			<Button
				variant="solid"
				theme="gray"
				icon-left="lucide-plus"
				label="New announcement"
				@click="openNew"
			/>
		</template>
	</AppHeader>

	<div class="px-3 py-5 pb-10 sm:px-5">
		<p class="mb-4 text-sm text-ink-gray-5">{{ subtitle }}</p>

		<DataTable
			:columns="columns"
			:rows="announcements"
			:row-key="(row: CS17Announcement) => row.name"
			:loading="listCall.loading && !listCall.data"
			empty="No announcements yet."
		>
			<template #cell-title="{ row }">
				<span class="truncate text-ink-gray-8">{{ row.title }}</span>
			</template>

			<template #cell-cohort="{ row }">
				<span class="truncate text-ink-gray-7">{{ row.cohort || 'All cohorts' }}</span>
			</template>

			<template #cell-alert_variant="{ row }">
				<span class="inline-flex items-center gap-2 text-ink-gray-7">
					<span
						class="size-2 shrink-0 rounded-full"
						:class="variantDot(row.alert_variant)"
						aria-hidden="true"
					/>
					{{ variantLabel(row.alert_variant) }}
				</span>
			</template>

			<template #cell-status="{ row }">
				<Badge
					:label="publishStatus(row)"
					:theme="publishStatusTheme(publishStatus(row))"
					variant="subtle"
				/>
			</template>

			<template #cell-published="{ row }">
				<span class="text-ink-gray-6">{{ publishedAt(row) }}</span>
			</template>

			<template #cell-actions="{ row }">
				<div class="flex items-center justify-end gap-1">
					<Button
						icon="lucide-eye"
						:aria-label="`Preview ${row.title}`"
						@click.stop="previewTarget = row"
					/>
					<template v-if="!row.is_published">
						<Button
							icon="lucide-pencil"
							:aria-label="`Edit ${row.title}`"
							@click.stop="openEdit(row)"
						/>
						<Button
							variant="outline"
							label="Publish"
							@click.stop="publishTarget = row"
						/>
					</template>
					<Button
						icon="lucide-trash-2"
						:aria-label="`Delete ${row.title}`"
						@click.stop="deleteTarget = row"
					/>
				</div>
			</template>
		</DataTable>
	</div>

	<AnnouncementFormDialog
		:open="formOpen"
		:announcement="editTarget"
		:cohorts="cohorts"
		@update:open="onFormOpen"
		@saved="onSaved"
	/>

	<PublishAnnouncementDialog
		:open="Boolean(publishTarget)"
		:announcement="publishTarget"
		@update:open="(open: boolean) => open || (publishTarget = null)"
		@published="onPublished"
	/>

	<DeleteAnnouncementDialog
		:open="Boolean(deleteTarget)"
		:announcement="deleteTarget"
		@update:open="(open: boolean) => open || (deleteTarget = null)"
		@deleted="listCall.reload()"
	/>

	<PreviewAnnouncementDialog
		:open="Boolean(previewTarget)"
		:announcement="previewTarget"
		@update:open="(open: boolean) => open || (previewTarget = null)"
	/>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { Badge, Button, toast, useCall, useList } from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import DataTable, { type Column } from '@/components/common/DataTable.vue'
import AnnouncementFormDialog from '@/components/faculty/AnnouncementFormDialog.vue'
import DeleteAnnouncementDialog from '@/components/faculty/DeleteAnnouncementDialog.vue'
import PreviewAnnouncementDialog from '@/components/faculty/PreviewAnnouncementDialog.vue'
import PublishAnnouncementDialog from '@/components/faculty/PublishAnnouncementDialog.vue'
import { formatDate, formatDateTime } from '@/lib/dates'
import type { AlertVariant, CS17Announcement } from '@/types'

/** Where an announcement sits on the draft → scheduled → published ladder. */
type PublishStatus = 'Draft' | 'Scheduled' | 'Published'

const columns: Column[] = [
	{ header: 'Title', key: 'title', variant: 'primary' },
	{ header: 'Cohort', key: 'cohort', width: '9rem' },
	{ header: 'Variant', key: 'alert_variant', width: '8rem' },
	{ header: 'Status', key: 'status', width: '8rem' },
	{ header: 'Published', key: 'published', width: '10rem' },
	{ header: '', key: 'actions', variant: 'actions', width: '13rem', align: 'right' },
]

const listCall = useCall<CS17Announcement[]>({
	url: '/api/v2/method/cs17_portal.api.get_faculty_announcements',
})

const announcements = computed(() => listCall.data ?? [])

const subtitle = computed(() => {
	const count = announcements.value.length
	return `${count} ${count === 1 ? 'announcement' : 'announcements'}`
})

const cohortList = useList<{ name: string }>({
	doctype: 'CS17 Cohort',
	fields: ['name'],
	orderBy: 'name asc',
	limit: 100,
})

const cohorts = computed(() => (cohortList.data ?? []).map((cohort) => cohort.name))

const formOpen = ref(false)
const editTarget = ref<CS17Announcement | null>(null)
const publishTarget = ref<CS17Announcement | null>(null)
const deleteTarget = ref<CS17Announcement | null>(null)
const previewTarget = ref<CS17Announcement | null>(null)

function openNew() {
	editTarget.value = null
	formOpen.value = true
}

function openEdit(announcement: CS17Announcement) {
	editTarget.value = announcement
	formOpen.value = true
}

function onFormOpen(open: boolean) {
	formOpen.value = open
	// Clearing on close, not on open: `openEdit` sets the target first.
	if (!open) editTarget.value = null
}

function onSaved() {
	toast.success(editTarget.value ? 'Announcement updated' : 'Announcement created')
	listCall.reload()
}

function onPublished() {
	toast.success('Announcement published')
	listCall.reload()
}

/**
 * Published wins over a leftover `publish_on`: the backend clears the schedule
 * when it publishes, but a row written before that did not.
 */
function publishStatus(announcement: CS17Announcement): PublishStatus {
	if (announcement.is_published) return 'Published'
	return announcement.publish_on ? 'Scheduled' : 'Draft'
}

/** The same ladder the faculty assignments table uses, so the two agree. */
function publishStatusTheme(status: PublishStatus): 'gray' | 'green' | 'amber' {
	if (status === 'Published') return 'green'
	return status === 'Scheduled' ? 'amber' : 'gray'
}

/** The date column carries whichever date the status implies. */
function publishedAt(announcement: CS17Announcement): string {
	if (announcement.is_published) return formatDate(announcement.published_date) || '—'
	return announcement.publish_on ? formatDateTime(announcement.publish_on) : '—'
}

const VARIANT_DOTS: Record<AlertVariant, string> = {
	info: 'bg-surface-blue-7',
	warning: 'bg-surface-amber-7',
	error: 'bg-surface-red-7',
}

function variantDot(variant: string): string {
	return VARIANT_DOTS[variant as AlertVariant] ?? VARIANT_DOTS.info
}

function variantLabel(variant: string): string {
	return variant ? variant[0].toUpperCase() + variant.slice(1) : 'Info'
}
</script>

// dashboard/src/faculty/FacultyAnnouncementsPage.tsx
import { useState } from "react";
import { useFrappeGetCall, useFrappeGetDocList } from "frappe-react-sdk";
import ResponsiveTable, { type Column } from "@/components/ui/ResponsiveTable";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Eye, Pencil, Plus, Trash2 } from "lucide-react";
import { formatDate, formatDateTime } from "@/lib/dayjs";
import CreateAnnouncementDialog from "@/faculty/CreateAnnouncementDialog";
import DeleteAnnouncementDialog from "@/faculty/DeleteAnnouncementDialog";
import PreviewAnnouncementDialog from "@/faculty/PreviewAnnouncementDialog";
import PublishAnnouncementDialog from "@/faculty/PublishAnnouncementDialog";

interface FacultyAnnouncement {
  name: string;
  title: string;
  content: string;
  alert_variant: string;
  cohort: string | null;
  is_dismissible: number;
  is_published: number;
  published_date: string | null;
  publish_on: string | null;
}

const variantColor: Record<string, string> = {
  error: "bg-red-500",
  warning: "bg-yellow-400",
  info: "bg-blue-500",
};

export default function FacultyAnnouncementsPage() {
  const [createOpen, setCreateOpen] = useState(false);
  const [editTarget, setEditTarget] = useState<FacultyAnnouncement | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<FacultyAnnouncement | null>(
    null,
  );
  const [previewTarget, setPreviewTarget] =
    useState<FacultyAnnouncement | null>(null);

  function openNew() {
    setEditTarget(null);
    setCreateOpen(true);
  }

  function openEdit(announcement: FacultyAnnouncement) {
    setEditTarget(announcement);
    setCreateOpen(true);
  }

  const { data: cohortDocs } = useFrappeGetDocList("CS17 Cohort", {
    fields: ["name"],
    limit: 0,
  });
  const cohorts = (cohortDocs ?? []).map((c) => c.name);

  const { data, isLoading, mutate } = useFrappeGetCall<{
    message: FacultyAnnouncement[];
  }>("cs17_portal.api.get_faculty_announcements", {});
  const announcements = data?.message ?? [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Announcements</h1>
          <p className="text-sm text-muted-foreground mt-1">
            {announcements.length} total
          </p>
        </div>
        <Button onClick={openNew}>
          <Plus className="w-4 h-4 mr-1.5" />
          New Announcement
        </Button>
      </div>

      <div className="md:bg-background md:border md:border-border md:rounded-xl md:p-5">
        {isLoading ? (
          <div className="space-y-2">
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
          </div>
        ) : (
          <AnnouncementTable
            announcements={announcements}
            onChange={mutate}
            onEdit={openEdit}
            onDelete={setDeleteTarget}
            onPreview={setPreviewTarget}
          />
        )}
      </div>

      <CreateAnnouncementDialog
        open={createOpen}
        onOpenChange={(open) => {
          setCreateOpen(open);
          if (!open) setEditTarget(null);
        }}
        cohorts={cohorts}
        onCreated={mutate}
        editTarget={editTarget}
      />

      {deleteTarget && (
        <DeleteAnnouncementDialog
          open={!!deleteTarget}
          onOpenChange={(open) => !open && setDeleteTarget(null)}
          announcement={deleteTarget}
          onSuccess={mutate}
        />
      )}

      <PreviewAnnouncementDialog
        open={!!previewTarget}
        onOpenChange={(open) => !open && setPreviewTarget(null)}
        announcement={previewTarget}
      />
    </div>
  );
}

function AnnouncementTable({
  announcements,
  onChange,
  onEdit,
  onDelete,
  onPreview,
}: {
  announcements: FacultyAnnouncement[];
  onChange: () => void;
  onEdit: (announcement: FacultyAnnouncement) => void;
  onDelete: (announcement: FacultyAnnouncement) => void;
  onPreview: (announcement: FacultyAnnouncement) => void;
}) {
  const [publishTarget, setPublishTarget] =
    useState<FacultyAnnouncement | null>(null);

  const columns: Column<FacultyAnnouncement>[] = [
    {
      header: "Title",
      variant: "primary",
      cell: (a) => a.title,
    },
    {
      header: "Cohort",
      cellClassName: "text-sm text-muted-foreground",
      cell: (a) => a.cohort ?? "All cohorts",
    },
    {
      header: "Variant",
      cell: (a) => (
        <span className="flex items-center gap-2 text-sm capitalize">
          <span
            className={`w-2 h-2 rounded-full ${
              variantColor[a.alert_variant] ?? variantColor.info
            }`}
          />
          {a.alert_variant}
        </span>
      ),
    },
    {
      header: "Status",
      cell: (a) => <StatusBadge announcement={a} />,
    },
    {
      header: "",
      variant: "actions",
      cellClassName: "text-right",
      cell: (a) => (
        <div className="flex items-center justify-end gap-2">
          <Button
            size="sm"
            variant="ghost"
            aria-label={`Preview ${a.title}`}
            onClick={() => onPreview(a)}
          >
            <Eye className="w-4 h-4 text-muted-foreground" />
          </Button>
          {!a.is_published && (
            <>
              <Button
                size="sm"
                variant="ghost"
                aria-label={`Edit ${a.title}`}
                onClick={() => onEdit(a)}
              >
                <Pencil className="w-4 h-4 text-muted-foreground" />
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => setPublishTarget(a)}
              >
                Publish
              </Button>
            </>
          )}
          <Button
            size="sm"
            variant="ghost"
            aria-label={`Delete ${a.title}`}
            onClick={() => onDelete(a)}
          >
            <Trash2 className="w-4 h-4 text-muted-foreground" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <>
    <ResponsiveTable
      columns={columns}
      rows={announcements}
      rowKey={(a) => a.name}
      empty="No announcements yet."
    />

    {publishTarget && (
      <PublishAnnouncementDialog
        open={!!publishTarget}
        onOpenChange={(open) => !open && setPublishTarget(null)}
        announcement={publishTarget}
        onSuccess={onChange}
      />
    )}
    </>
  );
}

function StatusBadge({ announcement }: { announcement: FacultyAnnouncement }) {
  if (announcement.is_published)
    return (
      <div className="flex flex-col items-start gap-1">
        <Badge>Published</Badge>
        {announcement.published_date && (
          <span className="text-xs text-muted-foreground">
            {formatDate(announcement.published_date)}
          </span>
        )}
      </div>
    );
  if (announcement.publish_on)
    return (
      <div className="flex flex-col items-start gap-1">
        <Badge variant="secondary">Scheduled</Badge>
        <span className="text-xs text-muted-foreground">
          {formatDateTime(announcement.publish_on)}
        </span>
      </div>
    );
  return <Badge variant="outline">Draft</Badge>;
}
