// dashboard/src/components/faculty/PreviewAnnouncementDialog.vue
<template>
	<Dialog
		:open="open"
		title="Preview"
		message="How students will see this announcement."
		size="xl"
		@update:open="emit('update:open', $event)"
	>
		<AnnouncementPreview
			v-if="announcement"
			:title="announcement.title"
			:content="announcement.content"
			:variant="announcement.alert_variant"
			:dismissible="Boolean(announcement.is_dismissible)"
		/>
	</Dialog>
</template>

<script setup lang="ts">
import { Dialog } from 'frappe-ui'
import AnnouncementPreview from '@/components/faculty/AnnouncementPreview.vue'
import type { CS17Announcement } from '@/types'

defineProps<{
	open: boolean
	announcement?: CS17Announcement | null
}>()

const emit = defineEmits<{ 'update:open': [value: boolean] }>()
</script>

// dashboard/src/faculty/PreviewAnnouncementDialog.tsx
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import AnnouncementPreview, {
  type AnnouncementDraft,
} from "@/faculty/AnnouncementPreview";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  announcement: AnnouncementDraft | null;
}

export default function PreviewAnnouncementDialog({
  open,
  onOpenChange,
  announcement,
}: Props) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Preview</DialogTitle>
          <DialogDescription>How students will see this announcement.</DialogDescription>
        </DialogHeader>
        {announcement && <AnnouncementPreview draft={announcement} />}
      </DialogContent>
    </Dialog>
  );
}
