// dashboard/src/components/faculty/PublishAnnouncementDialog.vue
<template>
	<Dialog
		:open="open"
		:title="`Publish: ${announcement?.title ?? 'Announcement'}`"
		size="md"
		@update:open="emit('update:open', $event)"
	>
		<template #default>
			<PublishFields
				v-model:mode="mode"
				v-model:publish-on="publishOn"
				hint="Published announcements are visible to students in the cohort."
			/>
			<ErrorMessage class="mt-3" :message="error" />
		</template>

		<template #actions="{ close }">
			<div class="flex justify-end gap-2">
				<Button label="Cancel" @click="close" />
				<Button
					variant="solid"
					theme="gray"
					label="Save"
					:loading="publishCall.loading"
					@click="publish"
				/>
			</div>
		</template>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button, Dialog, ErrorMessage, useCall } from 'frappe-ui'
import PublishFields from '@/components/common/PublishFields.vue'
import { toFrappeDatetime } from '@/lib/dates'
import { frappeErrorMessage } from '@/lib/frappeError'
import type { CS17Announcement, PublishMode } from '@/types'

const props = defineProps<{
	open: boolean
	announcement?: CS17Announcement | null
}>()

const emit = defineEmits<{
	'update:open': [value: boolean]
	published: []
}>()

// Publishing never offers "draft" — `PublishFields` drops that option unless
// `include-draft` is set, which is why this dialog starts at "now".
const mode = ref<PublishMode>('now')
const publishOn = ref('')
const error = ref('')

const publishCall = useCall<
	null,
	{ announcement: string; publish: PublishMode; publish_on: string }
>({
	url: '/api/v2/method/cs17_portal.api.publish_announcement',
	method: 'POST',
	immediate: false,
	onError: (err) => {
		error.value = frappeErrorMessage(err, 'Could not publish the announcement.')
	},
})

watch(
	() => props.open,
	(open) => {
		if (!open) return
		mode.value = 'now'
		publishOn.value = ''
		error.value = ''
	},
)

async function publish() {
	if (!props.announcement) return
	if (mode.value === 'schedule' && !publishOn.value) {
		error.value = 'Pick a publish date.'
		return
	}
	error.value = ''

	await publishCall.submit({
		announcement: props.announcement.name,
		publish: mode.value,
		publish_on: toFrappeDatetime(publishOn.value),
	})
	if (publishCall.error) return

	emit('published')
	emit('update:open', false)
}
</script>

// dashboard/src/faculty/PublishAnnouncementDialog.tsx
import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useFrappePostCall } from "frappe-react-sdk";
import PublishScheduleFields from "@/faculty/PublishScheduleFields";
import { toFrappeDatetime } from "@/lib/datetime";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  announcement: { name: string; title: string } | null;
  onSuccess: () => void;
}

export default function PublishAnnouncementDialog({
  open,
  onOpenChange,
  announcement,
  onSuccess,
}: Props) {
  const [publish, setPublish] = useState("now");
  const [publishOn, setPublishOn] = useState("");
  const [error, setError] = useState<string | null>(null);
  const { call, loading } = useFrappePostCall(
    "cs17_portal.api.publish_announcement",
  );

  useEffect(() => {
    setPublish("now");
    setPublishOn("");
    setError(null);
  }, [announcement]);

  async function handlePublish() {
    setError(null);
    if (publish === "schedule" && !publishOn) {
      setError("Pick a publish date.");
      return;
    }
    try {
      await call({
        announcement: announcement!.name,
        publish,
        publish_on: toFrappeDatetime(publishOn),
      });
      onSuccess();
      onOpenChange(false);
    } catch (err: any) {
      setError(err?.message ?? "Could not publish the announcement.");
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            Publish: {announcement?.title ?? "Announcement"}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <PublishScheduleFields
            publish={publish}
            onPublishChange={setPublish}
            publishOn={publishOn}
            onPublishOnChange={(value) => {
              setError(null);
              setPublishOn(value);
            }}
            hint="Published announcements are visible to students in the cohort."
          />

          {error && <p className="text-sm text-destructive">{error}</p>}

          <Button onClick={handlePublish} disabled={loading} className="w-full">
            {loading ? "Saving…" : "Save"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
