// dashboard/src/components/faculty/PublishAssignmentDialog.vue
<template>
	<Dialog
		:open="open"
		:title="`Publish: ${assignment?.title ?? 'Assignment'}`"
		@update:open="emit('update:open', $event)"
	>
		<div class="space-y-4">
			<PublishFields
				v-model:mode="mode"
				v-model:publish-on="publishOn"
				hint="Published assignments are visible to students in the cohort."
			/>
			<ErrorMessage :message="error" />
		</div>

		<template #actions>
			<Button
				class="w-full"
				variant="solid"
				theme="gray"
				label="Save"
				:loading="publishCall.loading"
				@click="handlePublish"
			/>
		</template>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button, Dialog, ErrorMessage, toast, useCall } from 'frappe-ui'
import PublishFields from '@/components/common/PublishFields.vue'
import { toFrappeDatetime } from '@/lib/dates'
import { frappeErrorMessage } from '@/lib/frappeError'
import type { PublishMode } from '@/types'

const props = defineProps<{
	open: boolean
	assignment: { name: string; title: string } | null
}>()

const emit = defineEmits<{ 'update:open': [value: boolean]; success: [] }>()

const mode = ref<PublishMode>('now')
const publishOn = ref('')
const error = ref('')

const publishCall = useCall<null, { assignment: string; publish: string; publish_on: string }>({
	url: '/api/v2/method/cs17_portal.api.publish_assignment',
	method: 'POST',
	immediate: false,
})

// A reschedule opens the same dialog against a different assignment, so the
// form starts over whenever the target changes rather than only on mount.
watch(
	() => props.assignment,
	() => {
		mode.value = 'now'
		publishOn.value = ''
		error.value = ''
	},
)

watch([mode, publishOn], () => {
	error.value = ''
})

async function handlePublish() {
	const target = props.assignment
	if (!target) return
	if (mode.value === 'schedule' && !publishOn.value) {
		error.value = 'Pick a publish date.'
		return
	}

	await publishCall.submit({
		assignment: target.name,
		publish: mode.value,
		publish_on: toFrappeDatetime(publishOn.value),
	})
	if (publishCall.error) {
		error.value = frappeErrorMessage(publishCall.error, 'Could not publish the assignment.')
		return
	}

	toast.success(mode.value === 'schedule' ? 'Assignment scheduled' : 'Assignment published')
	emit('success')
	emit('update:open', false)
}
</script>

// dashboard/src/faculty/PublishAssignmentDialog.tsx
import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useFrappePostCall } from "frappe-react-sdk";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  assignment: { name: string; title: string } | null;
  onSuccess: () => void;
}

const PUBLISH_MODES = [
  { value: "now", label: "Publish Now" },
  { value: "schedule", label: "Schedule" },
];

function toFrappeDatetime(value: string): string {
  return value ? value.replace("T", " ") + ":00" : "";
}

export default function PublishAssignmentDialog({
  open,
  onOpenChange,
  assignment,
  onSuccess,
}: Props) {
  const [publish, setPublish] = useState("now");
  const [publishOn, setPublishOn] = useState("");
  const [error, setError] = useState<string | null>(null);
  const { call, loading } = useFrappePostCall(
    "cs17_portal.api.publish_assignment",
  );

  useEffect(() => {
    setPublish("now");
    setPublishOn("");
    setError(null);
  }, [assignment]);

  async function handlePublish() {
    setError(null);
    if (publish === "schedule" && !publishOn) {
      setError("Pick a publish date.");
      return;
    }
    try {
      await call({
        assignment: assignment!.name,
        publish,
        publish_on: toFrappeDatetime(publishOn),
      });
      onSuccess();
      onOpenChange(false);
    } catch (err: any) {
      setError(err?.message ?? "Could not publish the assignment.");
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Publish: {assignment?.title ?? "Assignment"}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <div>
            <label className="block text-sm font-medium mb-2">Publishing</label>
            <Select value={publish} onValueChange={setPublish}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {PUBLISH_MODES.map((mode) => (
                  <SelectItem key={mode.value} value={mode.value}>
                    {mode.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground mt-1.5">
              Published assignments are visible to students in the cohort.
            </p>
          </div>

          {publish === "schedule" && (
            <div>
              <label className="block text-sm font-medium mb-2">Publish On</label>
              <Input
                type="datetime-local"
                value={publishOn}
                onChange={(e) => {
                  setError(null);
                  setPublishOn(e.target.value);
                }}
              />
            </div>
          )}

          {error && <p className="text-sm text-destructive">{error}</p>}

          <Button onClick={handlePublish} disabled={loading} className="w-full">
            {loading ? "Saving…" : "Save"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
